---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-postgres-user
  namespace: media
spec:
  encryptedData:
    SONARR__POSTGRES__PASSWORD: AgBLHyWYuiJgI2lXmsLbs2LxV8BtrLWGcEgm2OnwySzEnhWUZQRdlW3Wo63tobMx3yNWg+2MUlVzCukBYIZ66D6HYxUeuZMw00+2umaSfA3l6IiptvELCe9JZDZYij3pqxeJvmf6oLvzYKFBZg/D1Wv+vP0yQ5TViOZXS22goGO/wlE8OfaUxPwhxFiI4oHyO/GeuZzeVFjAmdaunx/yEycSjCi5Zu34XraBHa6iFYBIf5eSoPhK9YdpRHjBiB6zWJ/ROY0k5AgXWraCfD6GWj/ZGZHtDhzL5n4qTYvMZBGnykmBKdTAmwUYb0orIO8o9QTz/jdcnnhhqswllPscQqVxOPCdtOYbA0PbyoYaEE9LTDkv1HspywsDoJRUrLKCjW+zU20dPRMH7iyAKFVfZJU0wMuLQz51Hwl1qYgwyt1OGGtGfms1jMfjIc0G8025GymBMwk+iwqPOU4CjnkOYDaLEyJRuvJ4J7nLjZyTWPoO6XrW1DGG6swAV6eNU1hFT+giL8Tpjr2MP82UpO9PWlvmnu6P/b7EmLkoBMi03TLjmQZr+b864BRwRXkYl561kEnp4S2gwVCXuodnnXXO/Bi73iINDWRIxYCoq0PQHvnvlHs9ZKl5xCtQHcybQsjKDEP3rIkUn+XlMHlzn1vzn8bZ4H5RkJrlOOCUqgQ9fMP1xDpenkwOqHKn0vmJ3VvZojVgTTGTCEK6miLNINzGYfOzCAde7fWPJCaPnLl2oxQ=
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-postgres-user
      namespace: media
    type: kubernetes.io/basic-auth
