---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-postgres-user
  namespace: media
spec:
  encryptedData:
    SONARR__POSTGRES__PASSWORD: AgBqwid6lR/ZxafYeKZPUDqALTvwZG37oBYoVupcgfFvvdinUia01rtOOc4bRW196iSQmrCu0ZPNcYfoKh6GcxhVmkHVk4BQwgT/AOjRBjH3t5kEbUuXoTmyjRgkmlHYeoyd6BbF2dAp27Y+5525FoMMc6a6ulfMh2PIo7i/bt0BL5aQ0GuCb4kadIcRDtL/WSdtXCUG921cuVUbsXPDcuKlKUb1XG6BdRBKmEAkyURTe4fpUvtRY7NR2oimPlGMHQa9ny9e8Pj4ubl0FQzMGxSu8IpDTm5HM5FZbzqQMmz4GKUW8nE1xcFHke3YvvQbVHWpfcDAX1gy8Y3GUM1ZYq473DUFz762XGHV/mBRWnqe0BgvNqFappGSuG42RkOOgZ20DRgwVXnYFTsbgileglb2SRm7DwIhqOe1LtAg4oPoDn677gdumGGZA66qkGvRL+fbHuvhqnCN0uq5FdMrBQlZcGS2tILh5AqHdkHb2YhR8LueTI04FMpoHWTmwoK7HOfOKaWsujGqPDyesqx1O5mmLrescTIEFngsCduWdZV84plULEboIpLcv067BfHu0ZTNhd8UsUFUfCwAAF7I4zbZNuIgYeYF98mjPOeLkzMd68GZ5TaogrHBMQNCPZo/W4h2WXDl+jkZBCiao3hN0uiC73E56pKtAs8RL2N0WOamtBsyE8IFTqEGIbzZtYK1jroL1UYNI+1aF2GfEEJEh77RzpS13NI1QdmJtO4/+zY=
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-postgres-user
      namespace: media
