---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-postgres-user
  namespace: media
spec:
  encryptedData:
    SONARR__POSTGRES__PASSWORD: AgAH1gqdiM8sJ24d8FPE2Dym3nN8DZrpb9jO5JyeXtVh7Ym3rp0xnjqVQ/evSXEvRu4OiRlVcAY+ffQKP6mIEXDu6iLxCarQhk9CdCvN5namznARfJIrMCLTXjKv2z88MKlnzWRLnXWi40iAfMOlxf2ze2am2QcrDa4fmwepyJuTcX7x+c8yMPANRRuA6MrJGRmmbgCeAcIpVyLIvWvRNSFnC3RTu99/Y/XSSGB0ohwruIifdtxJP+E3O72Ckq0HzNTzQuPWdB9MSyqj9RxkT49AsBYVyZjsyktI/7saSKdeCelU1uDRpPMHuJQjsd+uz1ugTDOrU8v4RJPeEtvnuuiQSKaAaJTvGThQDdm0HRqSrq6yaHfiIciJePqCmMdZgGMsC54SDta2BgJyxOtF9V9PCcbXfBrNpH8dF3RrFXStHWx8O33h9kPnQCXS2N3dGrpY56QS1dGDcCvkiJ98U0dkU/2+Uryh7/VwlUJHE26JGlE+s12vzyo+oF5N6I0DBxIkB+f6+wA9eDlkDnkPdFU1UF07GlGJhz7HlNevyetLAt/rbL59SA49/LNubkS3uv6s/sMFIo3+h+HQiM0+CPUcJqCQCZOsZmYUx+QKvY8YlwgK7OBie88DxXHcbzcunkVs4wWQSgpogn0TEzbFozsJZaq6KMuUm26juXqhGhOxgBOhaRBsQgr5ttdmiqe3H23irnitPN+JTgSMziC+epBf1/pxd6bRh+2Tpz/w+QY=
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-postgres-user
      namespace: media
    type: kubernetes.io/basic-auth
