apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dio-local-issuer
spec:
  acme:
    email: wexder19@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: dio-local-issuer-account-key
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
      selector:
        dnsNames:
        - '*.codegrowers.local-k8s.tech'
