---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: digitalocean-dns
  namespace: default
spec:
  encryptedData:
    access-token: AgCoWEus+L1GXMjWG2Sdq3DO+HEPgCtwaavDCF8PjaQHY29bl4Ztvr3WgWseJJVNnHsLb/878OXFfXsdcgW43DtlIyzxFyrwqlUVgnKtiPaO+EgUmY9tJUwVQTxcz9C+izk9ICYZFqq5bSLSGLGD/0qh6IOHVLOIsZMAJTbxSm/xTOyLj9lkva8vLRpX0EtcY6WpbUNylcJHF3pSIunSmeAONlzcaTOc2RRPao/ZJWwT+hmtIjuuZKdNDY78Pg546wL8SbtgUQxCbko4EDr2QHU2J1UGl76Qc2ygMl/VEMxmcoAAlCb4yvpcswV9KlLeJWXxWuLPCX+YTtNZB4DvlI8JqNMq+D2LvzKrpiuqYPd9e0H37iTx41cmv7zl9a6wP97mWHUygpV+nhAWSEZCxvnJwh09TDj8Cttdr5mxqFgrlOuNRbFAUQgWwgySOWlvKIxY+mafine7buCq4t/nTrUUubjom8d5DnBDFn9cv1SVhJ5QbJHiquizF6Jo4/hWP2HPC2q1nCVDRhQhQjQ48diCTaEz6HPv7l9G9qAjcwpGpeySUVNsAJBzKE73tcmwNdmYCCWzwkKIxmH20ZsUpJUP/1WMgF67YaebLZNZlwisoy3WpuZDx3brsCeTwoe13KbFVSLv/6ZwasFyJajM1mjOwyQj9wrLU5GC5S0YMzOu5eHYwKjNb1kiOclj51jIwKAQgT2sIcgxyCCz3gog5gDQB4hR9FgNyH5maH8LAaOxuAcq3rPENeJR6S4y1O7IzZq6bfUfexJmC7dI0+TsmO9us9XtWKcNMg==
  template:
    metadata:
      creationTimestamp: null
      name: digitalocean-dns
      namespace: default
