apiVersion: apps/v1
kind: Deployment
metadata:
  name: solverr
  labels:
    app: solverr
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: solverr
  template:
    metadata:
      labels:
        app: solverr
    spec:
      containers:
        - name: solverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          command:   
          env:
            - name: LOG_LEVEL
              value: info
            - name: LOG_HTML
              value: "false"
            - name: CAPTCHA_SOLVER
              value: "none"
            - name: TZ
              value: "Europe/London"
          ports:
            - containerPort: 8191
