apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: transmission

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - wireguard-secret.yaml
  - route.yaml

configMapGenerator:
  - name: wireguard-config
    files:
      - tunnel.conf
