[Interface]
Address = 10.71.47.133/32,fc00:bbbb:bbbb:bb01::8:2f84/128
PrivateKey = ${PRIVATE_KEY}

[Peer]
PublicKey = ${PUBLIC_KEY}
AllowedIPs = 0.0.0.0/0,::0/0
Endpoint = 185.195.233.76:51820
PersistentKeepalive = 20
PreUp = ip route add 10.0.0.0/8 via 10.244.4.30 kev eth0
PostDown = ip route del 10.0.0.0/8 via 10.244.4.30 dev eth0
