---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-secret
  namespace: transmission
spec:
  encryptedData:
    tunnel.conf: AgCQJO4hY/GMIFznTaB7OZe0q2PqgPPdEBrJX5jkQjniwbHkqpcAAUXrN3EX/sCjbozsoFFJ1ltOGXeKednMElIfkh8BKijj0g95qeUBA6leBIHTstPsumL9AKbRjZwqKuNbCfs8PEMTQylgJi4V4EumJP1OHfRY8ijeIXrijpMDIGKMfh6cibSexx7WfX5Q1WcnSJg5AfopJBXflmoQwPQHaOJeKFLZGXGfNSlPxZbKxesIr8nE8yKDjQM0qln5CSgGgslVdx47RPVKY7ItGO7Om+rjVGA/9X67AKAKzJJZM7JsneFbcNlUQ88Vi5t10wDB6ZSkyySwy/jocBGvJL2L7QN+uuqC0ivGszT454Bxb8073nRH/jMS5vejqQx0j/pNaLA1NIBkJRtkQp50BpoPkUTcGJW/Z6JGlrxi7W4UJ4sVCp2A98/k2Y2jO+XQnFYHyRUZ7p2ImRK0A09m/oGcDS7LLaOLLtZBEpwdOzNo5FHGaaidiroVMlkIk+sGZE9FmNsnulHpdPvlrgu3ne8ZaGeX4p2VI4FspYKVCPY+c+xMw6ogSGAlxpfP6WeY+BBd1kNXt/qdPWVIfXA4tqqlYgyllEVWkJoD2slvD5fOQ860kfZaNy1yq9kKvgnqb1xSqsFg0H0djZs3t3dyaArHjGV4NNLfCyGYZeGauh/Lt/W/GCqzjPkG/teXxQQ3FBDBDWCuixyc3yruSD4pi3laFUd8au6o6KFezxS8xHKnvaCsIT2weK5RL5kJB7vigODgotp1B+k2q63Xz5vMqscAmHmaJF/9807L8rflNrKBLqg0kz2SnRCd+8jiXJhsJVI6PQnnf4PxatA+jphsvEv7RBKdf99OaTuj6LiSOWSPtAi9R7FIkoEtaoa8zQk+LcZD2ispxWuS49qS9UFD9hFdhAjO3nRABL1Kf9FROIDqzUeMMX14tQ7TatKAwxVWEEkr2ldWdJ9e/f53OIq5LBTgOh3TAkIwVxFebNBY71pMII5XifZ158nWhja0vFAcwLtK+Lfysjsc6AQWs3O2AoUe2y7UwWQgyCqNBbAChrZSoPg4xESHN44vMGlnArwEdkFqVzKOT3jzNGroT4L8Hma7hZ6RRWmWbhWK2d97gS9X/El0dvGvWLcaKJUujp0GV/J2CvyJ1Fzt7bGWLlrq+OOZzDbbUG2CP1XVMNDFY8TIAmPESWWBzC3jgSPoIA9TY6JZb2CJ8vuKcy31gbhR8/I4Ogtw0KyOKfLoRYo3TKcYNhKrCY1euzFKaUJh7n7wUEnApBKCKPUo/4rDLF78LIw/4t6lG2vY
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-secret
      namespace: transmission
