---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-secret
  namespace: transmission
spec:
  encryptedData:
    tunnel.conf: AgBOFSQlaDiZceN8tNgpTxYQrzUmTo7dqrHIkGF/XQdpANjzYjrzNHZ7G1nfpXSGDV2z33w3OB7Hfc7jN8dGg9Az5WvdrF4BIciJXUF0y1F5Na2UgQIGTHm9H4iDpGsuwgKnwVvnwIpBlquMBOg2BvC3j5banYPq6O5IDk1OwBQloc0pZBHotX5n6adnmUjasC4E2YxA3QNA5sx6LjdEf0JN+zo2ZD7i3Ad/muUvVrABuBfSKJEbU8LqMN2S4SHw4i5bNC0pKO/LQ6IYrbAui/jcryoLxXQtQgg1TPaYYnyYK5pOmajXNXj+T6PCG+IuGTIfBRo+vnMvbTepkaUbF+K6GQt1z7CMxg6NH34PNUMny5GL8xrbAlRUBv39xwDhVt61ILTAUxHpoA6Ec//byFN/o8w8vQQrE1DfybvTUmWRPQp45uznlaNW1j0tiIDO9v5luN2Ls0O5OsrsKoUlyxZWfAW1AdBYlpkA/Isk5K3r+DlGK/jm+Wd3Pt/TwcuIL0Aor9bQbgNYCUi8Bd4dEHPw7H6F5nakLsEQH1XeT9oZoO11tkwmven3gkUvwD0qm12I7phCgm5ptijQB+vcVaP7lX8MmdlGNwVakC5AnguKq0V/sD9QphvLIsIo+222ug8R0FdkiPSiSuSJ507LbJsR1YqLSfSOai+JHUrtG39d4pk/jE+sFaMR7IqM2Rl0F3hv0CnNXKdxbgdCnTkuqLnPpTh/xn8N+LsC+rsJp0ks7Qj7SccmYqgeRAS2WFYUc+KF6uU+7iLVbFRvgurA0pHOXUPxJi667hUynSVV3MsuDK2BIy5qHUOaZ9X1vJMxmfuCvA+vKdR9niXgX7GIngGYUPbSyNS6IzSdaCYtSDUHW0O5CMI0o2kxK2a84x9Q/kIKxdu7fWENgn3Ee8a76seUgHLWe/XjlC9DzYFkma8Tl2Ze/4RbkG8HmzDF5/0OSh0J/6CeV5ScSBceZju+Sq/mS7TzjInDtA8/yymMqQd5K/X7b3fEqqL48XIge9gcO6Q/4ucF3UQF+eDUCivoUIxrsoZpkxUtEWx+u913qGYs5RPYnA7dOsMxgvKHSMHZwjGKPhr5Fj+edUIC9FfrB837cqiyIBSJnCtLpHDkfvWXQvaVm2HxA0odKSQnvD2cjjjcas50hC3AKLFnq4Zu52knyctFYzO8O/NB3paRWjl3Gf8RGECz4om17fGuL3vuhnDXnSy5AZd2tKChITE=
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-secret
      namespace: transmission
