---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard-secret
  namespace: transmission
spec:
  encryptedData:
    tunnel.conf: AgBRNfVvEIJ08fiW2akGDyRv1jeV+cB5R7M+p6cMBlOd0f2rWM1z29PB/Hp4memWb56aj1/VEoeOUWEnDhxBu6UCFispZFMN801KkzqdattcKL650lZKVSejIXi+CnQqHTJaQ5QS/Yv3ZPYc+sPABqx7IWyymj4bmYbVik5kImK9/sIgPTamdUaIX0dzwvOzJY1z2ZM/aR8zDaqDXDlpoqV89+J8pxqlu+HIlN9ThBdTl1EchX7ffhTT8KGtJ5+XLvFPioy5q0kABdWw95XwsWN8KCsZD1se5510w0zXzL2+7LzVoSpz1QT3mKLbhJ4K0Km1KvusBHKMqJLUrvUyKBc45QTt524opfkCFN60IQIPOF1GqTOPVFmqrlSBMco7XIsoX0DLOci8u5yvb+jX/VOfROBK7IUOKCRmvi6h7MQmNcObhB28N4mgju2bL5QdgXL5jegvOz14Vp3ywPE+Cwd2ZwZXI5jGxyib5fHiqCdfgiuPzs6246uCjSrQ/QLqBGomvAIFjB0dXlZbSY/wuMtMB2mH9/nlXvOvrNTJhgK/2/jpky1B13wCV6h38HnCYACremrowgOChYg3ZdYpAWLqYQvvVc/qdMhHu0v5IqCWneAlQDfR84Y7hvwzymgUdGblchDWZ8AO4BfdCFjtGboF0Lhd/wThAy9VLnRU/G5m9BvRHmITCvpntW/GVgMCYO0YscdisifuslsGnv9Pno0+GsTEHmuCWu1OWFZdy/BVfSDeTUPVp61EPq2VEDfuRvAbi08RSRZXDqXi0TRyPs7MBO6TnyluRObSVgBRWTunCC/f6meNlaEcn0BPTJEkUVS9/v9NPWwniYC7mGhD50Ob88DVEQ6WZIBDlqy4hDoIXSWz2e/ALiJc76a659LDG7qQTp41+yNOPHt1hBo4Vk9lQHmHys5Cb2+jM2yW62ztew8XgLIXLB4eXmkrSiIdwdVnFdAyJUpcvnyADKUHsZ42r3t3YNjJ+Eb6dBKU548mmonwCfgN4eVE4+4TJ/Or2oW3ZK3Td/ollXylkI5Uzqw9xG3HhiZqNk+eoEan5xc9mPptM0ZAYdK9pwv+9gni4Jqb9L4V3zEmPECcVwPYktRz3jfBs0WCuSwHELGc89CxNyIjoSl+z8wrkI+p+ZWOGORa5pdwznPzqKGL5r7RE4zImHemimgploswaOWDVmGaksSFokmZsqzmqPQaTopCW+pSx1o10sCslsIVflx+ZO5I7X7d/f+xMP38Id93v8YWyWURzlB8XL0vErSespvkJtdyDkDaQG6CXtDxc3I5Cdo3b/6xhJKyJKxEfXs8e47xSEptFtMHVSv871ivsR+hHOxdfBILbpm73z/o6pVkrOAFUZuKGz9082oh8yW2UGygvnmSC54OccYUaxV0Z9b0HYGoAKa1TkKNt8bdaMGhZeCRfgdZ0NRQafCj80Jbj4/rjWKD4+hk7VR406dv6xvAyRwTbL/9LaFFGXR8gXUp1pLeUVCl8mfwDfXCk7m6aKr0EA==
  template:
    metadata:
      creationTimestamp: null
      name: wireguard-secret
      namespace: transmission
