apiVersion: v1
kind: Service
metadata:
  name: bazarr
  labels:
    app: bazarr
spec:
  ports:
    - port: 6767
      name: default
      targetPort: 6767
      protocol: TCP
    - port: 80
      name: tailscale
      targetPort: 6767
      protocol: TCP
  selector:
    app: bazarr
