apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr-tailscale
spec:
  defaultBackend:
    service:
      name: bazarr
      port:
        name: tailscale
  ingressClassName: tailscale
  tls:
  - hosts:
    - bazarr
