apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lazylibrarian-tailscale
spec:
  defaultBackend:
    service:
      name: lazylibrarian
      port:
        name: tailscale
  ingressClassName: tailscale-disabled
  tls:
  - hosts:
    - lazylibrarian
