apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: radarr-media
          nfs:
            server: 192.168.240.112
            path: /mnt/main_pool/private/media/movies
            readOnly: false
        - name: radarr-downloads
          nfs:
            server: 192.168.240.112
            path: /mnt/main_pool/private/downloads
            readOnly: false
      containers:
        - name: radarr
          image: ghcr.io/home-operations/radarr:rolling
          command:   
          ports:
            - containerPort: 7878
              name: http
          envFrom:
            - secretRef:
                name: radarr-postgres-user
          env:
            - name: RADARR__POSTGRES__HOST
              value: main-psql-rw.postgres.svc.cluster.local
            - name: RADARR__POSTGRES__PORT
              value: "5432"
            - name: RADARR__POSTGRES__USER
              value: radarr
            - name: RADARR__POSTGRES__HOST
              value: main-psql-rw.postgres.svc.cluster.local
            - name: RADARR__POSTGRES__MAINDB
              value: radarr-main
          volumeMounts:
            - mountPath: /downloads
              name: radarr-downloads
              readonly: false
            - mountPath: /movies/
              name: radarr-media
              readonly: false
