---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-postgres-user
  namespace: media
spec:
  encryptedData:
    RADARR__POSTGRES__PASSWORD: AgAEXwmnkTmbH4WC6Q5wqa5i32L2nJmHhxkcDispfdCaMoHTtWNqRvQpTwAbMWu9gBbBfrb4irAeRYBdvVLoPa6BXvf94D/50mh7Hmtz72MR0kMyiVOlvsipKynkTWTliaGpD9EgN7GlFpntermozeKibxsa0FO8ZOfUVL9MyhmovstnOlKeacq2aHY9D4SLkG7fhuTvRivfwH6NrcFcceEp1WC0E3PMqJo5g4ZR/iPk1NoQQdxoaKK1OZx8bWqmML77woXi0z7dp75hg9qoB0ew2715Xujyp604giBqJKHsHBVqxoK1jgjYPq5+B1aFjDr72LUzAriyZcgplKNwyEdYP2q5hHGuVV34ZsJhaohy/w/f57dsKyC1+p5ebF0M8yGKDaU9a3dipr//tEtSeTEVhlpT6Z1RuPI5qllsJsIhqZ2nXkn1oazIx5vMJd7bi1/GaDs+cjW4eRIT7hFK3hJAt94gz3PpxBbZCOYIqxpPRn9pYidXFFwevnGaBMa+MXnk+n9gaAMSBz6ozSnkzr8NItlR/THcSVSbYxhHOUffjxPt6xOJmWwjiA5Annk+b/oWrIdwy6Tjcp2/Wa0z2F6Zr1l5NTslQ86X6jLJnSxcaf8KcSlFcTZ767O3x+i0yCJ5Jm5R2cg4+H4ret4LFANathFsvbqEXRUhVYQabcMl1hiRQ3Aw8PO4nkGZ362GucGfFz+qOfe+cgNLP+AWb6Bo+fcfLQm3A22Vws4Mt9I=
  template:
    metadata:
      creationTimestamp: null
      name: radarr-postgres-user
      namespace: media
