---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-postgres-user
  namespace: media
spec:
  encryptedData:
    password: AgA1UtXQrOY4tnpiWEpBwZ42o0jRf9IB6eNk6pfOWxN4TZfzB/AGCoue3wp81Nmnvl8I0lrDp/vsCAJYHaW/4NvvDr0/TMigxXNOCczoSGLHrb6unNAMkWPvVu8NJnxJtFjQpY6jz1BRx9ysbX7QzWXnGs6u/dLUDiY7czGkD6wmhsygerOs8dGWHmzi5ob0D9Cu9K9rMtHU7/5r6cIzFHoKTaIIfGPOvPSYyfxXgpB7mD3zCamxE7RdpxAHBTCyCAESoTdczSS9WSOkMsAMOqzEzYdXFL9LTZbwlpfC539ofhLDLDCJ6GbnrUZN5JIuKb7efcmap1yrVL3vDSxisuEePsN7e5OF5fZcE4QisC3d1y3SKpVyVDd5j7t99Bn6maAlyDiOpJWVgyjUn9Azu2hLMHe2I69rgIeiwSZZlgKTd9FVz4qkwHQBShgAs1tgLKrxN5GCa4mdi6ECiOBpPDcofVnICAiMLQQL33z9m6DA3vPYQ7urJzslUNDm1gT4nnmBTycHv81Os/knl7V0954Z15Slb1D21OZsBovv+kWQeHbISqYU9eCvBm9ZS6ZkWq/qeolt94VdSwAG2mSm/WD96hhW2kpwXDefEl8KyMHE0HoD7NBmcx0cf4VAOQw6s3gLO8iRZM6OHM2+DDGNBbaYbTdgWZC1SMFaA4mCp68cy/r3BN8n59EUP2Srr6kFF/aqVR/wSYSo1DnU+pIij3MyvUKiGzEeMcCH5YA0om4=
    username: AgASMbOBzogpwtzMe1moqsX+2sjUOhSgUszcSwL/kxAgRM6cuyNBUkduEeRnC79foRmNOh5jD7TC5ZV5dEp0/TWD7zpSh3rRrqf28lJtGFs1+B9go6L1JSx3VgROykzFDRdxsF1hBzmhM4EqYrap5PhZMM0MbOELB08RX7nZPyTPuNNYUx1EGBB84mN8pLEQCZBtBlx3rZuOs1vswVaPE6yJn1c7Wu/531d7BANmFMk+qH96nCbQnlJVZdBHWC1TqBojRbAgq4ibukStTECmkwR6bw35x8hBtAufyct6CKEqdLbpEJ1I+v+7SrEp5xcqUES9gxQCGKlPbfIJTSbyNsVaB0aPwyOzy2kqw/v23UGkBosh3BOMXq01xrB7BHm6hXHXDVFUS86DcdtoV9nZlGgu5nW+X+22SWhYt+OC4b9Cc4LaR0bC4M375GPcJQ4l7CB0sZeOyMJzt3y5z4sGPuLpkIaN/bOsd533K2buSXDpZaTyTyUJz9Mndbl14ObHe0mxKTsz4C+4sy/1kKWTUWkjFRDL1G2m7eniJahDojS2x/N6xw+jgdIqXhdwIAxOlL7nY26ei0mhmgP8epw3yAY4Nf4+G8S/sHSiMo9x6/QEdyoPydbqg8P1J5cbbgH6DBqLzmPELTTA+V0i/CG/f/t6DN4IswWQEe8ynLjGpnEFu74MRcGgJKWWYW1OAN2feWAP1S9AuhI=
  template:
    metadata:
      creationTimestamp: null
      name: radarr-postgres-user
      namespace: media
    type: kubernetes.io/basic-auth
