---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-postgres-user
  namespace: postgres
spec:
  encryptedData:
    password: AgAXwp+WzBeOb6AOqRqpc6bfuUMV8kFi+Z6vCvJ6E8j1XMt4FNib7jfNUnPo6i18596XSHZQgzwsR0e+1bqejELXP2mAXKxg1Lz0rw852VxNWnYaOzrV+jRMQ96cPztTwTy3JqrgML3g7rP8l8zCkUEPy2L8vRUOhKB6frJseRvS3+yOnj1vPmkj9VxDz0uNSd9TCseNif9uC4itO9+H7Itn0OVhIp6ICOaT6O1UAu7TxG8bDXNtLuia2CXRkki9ls4tbozr/BzrPZ/Cbxl9e0AfhIKPyP9XoMCWIdR9cwmaGRRSpUfl61ygtbUbe3VNpNHSarc6kaAG+7jDHYW6eW3M7gSiOzwYgqqkzxsYE1zX338nW+yaZb01IB+x2dKnNGC+dc6WMx50PWAw2mpvgHysDLiAyjcVOxCTSvW02D3GQaBXzwCVLg3/EL0tLBxT1/qicYAFYSExpq+sRiKZTd0JgfTV9/eICxAIgFLgugnU9DjTv5UgFYNYjVoXFg7chmW9GHcO0Y1jEWWdI2Z72jeC+uKLbcOWw0l04rPs2II/RFkJdp1zpZRJSiuXt3NwusDAV7S2QA7VGBhKz/UfGHkgaNpNt2e8zfs9QUFdQOfzaUIaKi3bbi6IwgXcHKLWs9j2aUPDc0NpGItDRyOCvFEdrnZ6YgNaDa47qExRVRKWXd/dJJCGJAYMJWE0SKxHg98agYPHZ3XrAp93oZeOG0CcWyR8EOH25aPLR0+4tRA=
    username: AgCZ9RI5AXJcSHFP2fwJOGUT8I8s4AngdGBPWwFR3lSWa+QBFqh3ze/QWXtxB1juT3wczjXjsBNENHAb4epXn4hlPB1mBWQYfBQMy1+ciF+MkvxnDUSyw4c8VKdVm9cpLJRngfV3LQCj+PPrQ3AUCwyD3HNFdsYkvP9O2Vc48YaFKN+34iyaMToAe5na6zoCpd+o3BEMNCs4uBVHo4bMNjy+ci1bg6ollPSvpyf8RKEdcTJbFoXJDXLfNhZKDZN5DvqWvvaKEdNXxMo46O3VVWFKDW/WXHYUxZLg0P8UzXGhF5aU3l0hm5e6cEjJcLZYm+i6PpdVKsZYVJzi7y1zBOs8Upe4oOoelIqrF4b2foVSKJetrqPiw5EwxJ/6Xa3k/Ffp65nGBjaKqLg7Cla3RQTBppXbpnbHguQFzGbJ4lzYgAMv7FP5HMVpNp11XKHs/UGfj+T0N04Jv6okSwumZwMld6vawlcwVNv9UDhlvJqdjHg8e2GMtXyjd6Li6dbgTSiMaIaOq3fVCKQdKAJp3Hsw+9lBqyjjgpiVXtSZiyM7yOJncS6DEjbfHaW5YvAkBQ9uQnnGlHl67vkRcDuE0LoUUOPf9KiUWFqgjBGGFuP0D//LQAe9UUUomoUb2KLyhbUUHocJdIQmoRmitEJq5S6lJZFsCvoCQ6jxnnan9HFEdRo6lTIcuviiJ9O2TlDr+IC3nkGfdQg=
  template:
    metadata:
      creationTimestamp: null
      name: radarr-postgres-user
      namespace: postgres
    type: kubernetes.io/basic-auth
