---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: odoo-secret
  namespace: odoo
spec:
  encryptedData:
    PASSWORD: AgC+rZldEcSDnfWuz662zjIeOBfqxb1cSqCbejnpkSJdFJCo0LznDX4vGpqaP9Sxhp/RiIq14bQGQKAZMrC9ehck92bbxUfqRT6XQc3f2+3Sh2ycYDcYTxzjF/YDJ7uP6f6vgXWweWKyx6Ebls9CoM8Q/lO8k7WS8kspgO7rEqeozfjrsl3lR7sPWNw6C24p5ot3hLk2UxWSrOQ4BX6rKfN4lLtcz0R6vxq07rEYJ80wKH5xGNJM9pS7wfUQN6KokvCNI74tb3Tk4xygoBhpgmgkIuy1asdPaRn/W4soJVOSAodBvu8fSpZhHjhRZv7U0F7mFxqT9dOLJ+m/wPu4fsnNLkp0fj1ZcWzYBTNDr8gdYg9gnPPvCrUnBwElHtBS2VGHpRZgaoIFMIqxc8OQOgwBMCWf5oQt+iA62mdV9+iVkMDejush0dLSZl3bbP4S1wBV0iVyC/JoivWLTWkF16sccCrKfinGTtNo8xXal4j6L3IMbNh6idkA7wQvyVGdWZEGeJ/IbRkscTxg1KmWCb9osa6GpcXz6OlTKHNHKHbjO9h+G1HXY9zGFpPWBtcnnnKp5gRDwc8abwv8ovevfO58KtRxIYv1rY+6P830U+SJMKUiLZ0OD7S9emnD4D/F6RgqBjSzr30f55Kb3tRoJHyuhGrolu2ht1MXw9//yJ4yU3AUoAo9e34pks/Kr4JnJrPHM+IXk5Wb/KFMSsw/ZVO+H2mnjBQbWcczSsR+8Kg=
  template:
    metadata:
      creationTimestamp: null
      name: odoo-secret
      namespace: odoo
