trivy-operator:
  serviceMonitor:
    enabled: true
  trivy:
    server:
      resources:
        requests:
          cpu: 100m
          memory: 100M
        limits:
          cpu: 500m
          memory: 1Gi
    resources:
      requests:
        cpu: 100m
        memory: 100M
      limits:
        cpu: 500m
        memory: 1Gi
    ignoreUnfixed: true
    slow: false
  operator:
    metricsVulnIdEnabled: true
