apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-tailscale
spec:
  defaultBackend:
    service:
      name: argocd-server
      port:
        number: 80
  ingressClassName: tailscale
  tls:
  - hosts:
    - argo
