apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxies
  namespace: tailscale
subjects:
- kind: ServiceAccount
  name: proxies
  namespace: tailscale
roleRef:
  kind: Role
  name: proxies
  apiGroup: rbac.authorization.k8s.io
