apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: operator
    namespace: tailscale
rules:
    - apiGroups:
        - ""
      resources:
        - secrets
        - serviceaccounts
        - configmaps
      verbs:
        - '*'
    - apiGroups:
        - apps
      resources:
        - statefulsets
        - deployments
      verbs:
        - '*'
