---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAY5w4cki/cwh2A9HphobxNx4vXZImJbnPvMkoLmRu5yobJ3QyUX31JTqIQvgWuj8urQ+1d9TPWiSTzX9YYigmx5pPu0/tX5KtwWqECXYR+JPfYd+fCzB4kUS1xKZ4lmityo1ogJNWJB5kBMSou4y3Tomrqifcl2R16bsKNTXXqLcidSDzty8jsIn7xYcJPx6mWNUENt08bu7nrDMGIYCFMBt3VW/nx0p3fk8GOIaZDx0i5YD0Jp7Awft4yaoDv3fsDkoAALe7cIksQu7INV6rRS6lcU63gzjjlXvVU3lhss7a3BT0MtCEDPjrmDzqU95gG2CN+XDD+kqqU14g1Sqgwq85r6gmsXZw5ubRNlOlbNS4ZRmsOelQ5a2HUsfbbJAT6YkRXIfrYpwmxoCCyudk+NLckwbuL4dGWzsCGrNNln31R255/y73GsqhEoSnc5kPXsh5dQ75nIf/BEESXsIZSQ0KMeZnBQhiiingtjXJ1vtKmrjke3t6mipCoS6usYUexi3hdx8C5/O/QJV5/t8FukrCo/kcASn8JkedRrBVeKa0BtY3fy7EOenjP0HyXA9096ad3GuN7JdLJoyswrrpIJKoF2J5sJMihjw7kobdeWEQMLmdT8H6OVT/aqNmHYb4q3AR1wb+E78vMFEfGjk/5FY10q5UWvKuSFo+OpgyRGPpiL/3VWl0Npaso2djk9tbJEiv5iXIWhZhRzTA=
    client_secret: AgCe1sWqKsxtC3s8LyMW+gDcp8b7PCpdfwA1IU23+O5iBlX8HjasfxhBeQ/SVV2aw+PnqImWAybZ6nVnUHCSrFkdge3En8iPLCQuSjXpTIeSNgsFnV3U1DNWZjgnlM3mpr6dWhRiYpnJiGZx2/VKRFMlMPzGjzrcqwUJyImcuJwqPJdjVEdqE/Il6Cve9uER53Wvpj0A5QNlvvTMzLy9yrYOgEIM1SfKCOA+PzedcS1OASkj6TfS212SEvIZhsLPC2DyWm9MWaqoqoGKG3dsJjOisatJRFTY1G19D+4MAkEiGTeDQLo1XwCe5TZTRn0pdXzmIceH4UsFTSVAf5mCcK/MBpKjMY3niHFVDrhnP83VbHQaoGnoaOfODHqFCF5FKkn4CZcJIYXzkqt9+BsQycdZ1TgZp64Kiw/G9ayTAr1n2+620Q3oUWJ8Epp0ZvGHjBR0YABEEO+dEHK3fDT943KfMMcC3EK8JdrFRELklg7ip3TXz/vFG3qIQKsJABIYIRkXmWtKxbtMtWvQgRKntQuqs8jI+I88yw0+SU9l9voF8VFAL0GfZ4vj/XqDq9JSoVwrFeisaeC84FQ5mfRfJ7sVJPD3sUde4DT+2NGa6v/TseWvUFiNdpI+U7Z4OwLmJhqBnEg4BkEO3VT9SVWvoC3mH6zXvv7GxWucsa2+/h1fem4YJG4r9Cp7Zj5ykfJpszcAXiPj5+fIhF4AaA/67rOlMf0HFjs62Y+VciC/mimaBeEFvy4h59b6JUnht4zI0QNPzfIZND9OVvla+A==
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
