---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAZRDaa7bo1k7eVRCCU0KAGTrUO5Rfh5i8a6UU/2HkghRDg0jBmLke1i1ePZKDs2sJ7+bk5ae71/Ra//+hPW220D3R/nx+DB5dFiC5qO09/5eN4a2qeeMpYkZR7p8oRgeKlqQ6Wq81u1aFa0ua+h1uUO5NDceq5crL1xYyTIpXfPIUFaSUPga6z0fXVB0YdxiH23WFQV9GbIz75IFUGbMQubFLNPHpi8CgKh/twB1l97a7jeF8e5IcBPjdLg03tHbbXgVFO5/+JJ1BurGjaiOBViFX3JTEij/HDZkeOQgUAafyPKatHm1SLBlF79vZlzaW+FmpI9Ic0+iKLTCk3zmDU0uNajn+w4OukFVOBt8xTADeKJadQDduah515FZV2RJsg6VL3raGXOOZVtqiKqdpIHtdsVeG0rzd1nRYyRK0GotmnE21tJVXNN7jbl/jmmFmVW9Enezte4LKT5DZp5vwjM4hpB2S5v92FwT1aQBC1iklz7n5twGUBgCKlt8fOaIga6xMgmmzerRrde8mnY6Ow820+S2+RIrku03E1zkoVw6oKi2xQdTaxgWVDhfaf8ICpI5G5fIJiOAR8tTOe+fQ56iSj+hzKKaYYlYnK0lU8cytk+g8MoDZEcXco4jeT9AdavDZJ9drTcpEwTgI0xIlmzyuWZMmQ8hdlq58r0m78BuwEqF3Y/RU2TJRH2/35Ev2XRMpRDlcNAYBEWVeG0TyMvw==
    client_secret: AgAoTuYEzxFz+CMjCJ59IAecpzassRYA+SQmLVZSznp2rnuuhiG2QFXfz01K9HacUB4mLDF3jGwSo1HOF0+mBrOtREcjWnwGUNWDEUBLsxUn9lOSKwOhc5bSdGbl3Xe2PRkticVUGVEmYg0MW5wNXHG3woAX7c1h20PYkzI/QXI+1s2ACGh5PcPp+13+0+kLSyhc6yONA2B1E2GNwhbuhm/9Avi/OwiakjtX3gokK2bK39yr3Cb6Es4MKJ9+aVNChukwAGqmacNh15JXF9EF6hVqAXwc/OGTnTVbXvrIZdw3gIol99SizVUVKIoVqT2pG8X7sZua9iCXu29YRBURxewF05xNfVYFjpHY3av1U8yx7iplq/sGJJieKgkkizuIUPQzNvibE3V1sKpMH1uPqNDIhCxKq6y5MA6mce+yLOlukka+oNpJVZZKKRWfThLUgwttJKX9q7/nP2V6x2ejrG2bZJbWvpWX/sf6vi9TWWMnIgRZSOaBvoZvTpiBr2lVYZkDDn/fYFByT01ZwSPgLlwqhBlBJR6IFO8Namw0HJi2SmIchbOXh/8zb1NJFBPFhVpAS1prQwR2816JVYLjr2MTy3n/DF7OylPSau/VZBpLlTko7wu7b+Ju3tTGBnjDSUSSg7ELdweoX9oCqzxwx8Z2UlQBiD6cT7VP5tomDg41Ojof9dM/+1qY/J4oS/sLoTcv6dwvAQ8jZln5Cc2TWy2q0YvE/+upuXrl6wTKOofYuBDgFg35XQC6essyCn7ZdA319rNGtp4SYHolZDQmKddH
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
