---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBaVnyksBovdNoaGBG7NIavuLLr4gKwwZycyjPKab/EpZayOEqwEZX+uhNkWhgT8kK8NX81kb42thykTh9WJOWTPIIhNY0Ru/vTbLMiMCgbjuUHibouSYRlWXJHH6W8hJx1b/m/55+fTCgx6DqRJT+IEUUvM/ue/XRIZRZGN3FrhR8pugTLWGiOS2gR+DUdHbjfEHiumLbyi+iFCnARRPWFCvTnGh+V+E0tJG6Fr0OzGGFjjYQLS+03DsdCBzaoeQm3CEaC3ZfwxuyJuIf3yYF8KyPzD64HxMz/Re5VTHBIb/wJzfasbJKAaBy2CWcUcoMNW94GFe2Y+lWDNUcHIS5AUyBf0erpk79qYBq9oM0AuQtQd5ZpPxwbwZ8gqee4RmdNavPHIVsJg3IO42BAQlsYU8dsmLQnLX2Vl+AbSofhfnqxq8++wNW0ZvZZ/DF4BeYomCfEI6gOM/ByoMcDDLv9Dfi5wZvAe9hGK9ASS7NYaLlhuSZlVz3ITA3MqqaReG+vJWGLy6cEnl46wpl8dlGaRkMuOTuwGFJf6k3lQ3zj7GGxUcMXkB689gmVaMYPnwTfEJ6y8TYMOaNjt/lo/6DBX2xh1bwtnaY0vX17aZePkqbVcQHvh+AE+6WAXuFM8IR2qdsWqilxwKNTV9K5Tk2UUawtMFiGn4ZKRbBo9KNQmY9zS+NXzrsl9z/q6t9QYDjxxCjm3Kej6P+MdySchd64vg==
    client_secret: AgAHHTdVggHbd0bIOxyOw3RokCecsqZImQFY0lZiJfjjpc5cXT3yxfzcsjlmvMmy9UTkv2c/YUyx37/P3RibYMXi1uq8A/TWl7meO8m/NiFfjwBl01VAjfPg4XLDu0rhVounsISy2uwB8Fgg3aHkENGDw7R5vJbK42oK9ktt4wq+U8IrD4w31gUKwUl0iBGVmTzEka6aVmvjppnvlXomomByriRJ0t6i/APIj9wNItzyjHg4w+7O3cJQOm2uDHj3KuUT7hcFqkake6eVTGuUsGkVfXP5H5qtfxqrZZjRh2IAlPF7CyN8603ysE5Tj41RrMS658aFE4iBiXdx9k/c/qfP5JJJkusmjCUdaA21E+fNha1UiX+Zx9ZFaX15RTqF119JB3VTTWwm68DsGx7iWsVFGDQBDhB3kBVwAyMKVH1I0k2Dzv4Tk8ak82nUsCuPCFnwqiyMyB2MkIcGg5oMhLbz01c2da0EsSnbxGX9q80Y0VQootwHXkTcl+gzHxj+atAjIQ7Nk2UoCABQhp49DgF1xNp560x7JWF/kf7siNqnYWvgQFsMI+SI995aYlN9FBEyRqXBP95jQ2alsfkd+PHJwG72ybN7573fs4464I7FiPlwuEgpNKD4f9MSweqa0VRTUIFymDCX+j6kwYvRst3MCP3PLkKnnJJDa3ac82Dw2jM7cY7mKHsvFPy5Ny+LZAMIv3KqHVAZ/jdh6lqsMvj/8V4cDQ1UwQwnH4dF38P7IVXJpEm/TxtIqyB9UpNAnxV/yd+HEprVHWlIhwAfm26j
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
