---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAIc8R7JHaXQiekEWkZxH4x1dX+GjL9Wbzdh0tre7C+AezataHJ7gTC/S6z2zIOeK5O1PZRpECX/ZF2GKCH3gSaNsj23DRkpKdXrKKW/gR3wTUK48yX/L7CqDzfK82H5jsFsrLTT7A+DTiQHFX9hOermnSgKcDuW5OjM9cwu/oldqm/2vBZARVWqzBBLV6zad58ZIP5WV4x3o9HgNAfr0+1IVcnFvUxrsl4gMAKElu8GxBGJnnzYvtCpp9JWe3beENDG15itBfvpcXlM1wkWfpummp0lwxsN+SH2Dzxx0/uSqq6q7PlUPCB/HlXuQ2qkLvtbdJ6m287R4zaL33A0vFsD0ywudghjFuQIyMks4uWxak0XhPS9awqsn2H7fPifa2zzlSZGtgRT5e1forE+srPCRWtEeF2Px3q7I+anoOv/Et5k0fj7kRxThXAMEMvb2+NlPdaTBet8SACQqDcXBApn/a7lBPftlJhbA5IlI1pd4JqAXd/6VQHN4d6ggz7zFJxJ1Wu5ccHoWXOdzrLH481AvOXD8kcnGKEP4DXsGn3EF3zVR80VCb57shfCKsv/xRZu0SIvtZ7ad78Ydib9t7yWg+1vz3oS1oPJoGoZTflwFKx4jdLB0m0MRhzULeNtmAAVPMe0i6bbmXI603qJCETOJdnTYl8i/NyCKk+ZFxU4v9+KE+0jNsQT4eAG+dzSKKK/hwb7E1SK7cc4Kw=
    client_secret: AgBzEYiRvfAJ8QxN5y0PdyPRTR3zooyExgK+besb4b6kDvMTv4Atc58kTWHV3dTqq38PKx5tgtlB236/HwXPhW/7PAJp+f4cqRwMk1Lyf8oMybwfGSuw4jXSgHylZxyQJxIxLnSY+kRF3phTQDqGp/PmnbQj6tmisrmH2/0NnPI6Ot8u7n/xxlwsz27MGOXySKptGaRYtjsabY6wJOrOMP6AXQUAU8V9fB2gcwQjtQHM5Z5LUcRUBu7F0d+dJv72IgiSlsX4OfAAHrLHJhMWohTd3FnCHNb49OqvIoIFHVcqueFr0noCYL/NYYJy9CT6bzlPnWuaagtAEVx2mIgRB+S2O1X1KTf4LbHrM9SexfD+lYGHEai5KTPs1h6FnfksdiswVgHrKkXqogeotLb75HIsE5pH89oNpetUvmAEMRqsTekpP4WTMTtK0sFthko7uwEyyZl0/H+yUs39gj4r+3Uti+KAVAqHrqHRY8Qlz1bMaMZ+N+7t5BVWWA4H8PjwnODccKLuYXKqefMTki53WZoBoJK1jDD936RkobWLkwbRVAmWPB3Sw7Z6jgzzP87n9+gSizRDFgLZ7roVD/FZlLVnT1prfeHavJ+5thD+Mjp8sCoYE+E7KRhHlKh6hMLo9L2ctjUFIah6wQxK7Y52HK5YCfSWErhd0MaYeei2u3y4jxUNyTDtCYYBfsPrYIp4OaTgj+aZoeOUdyn2jB/0IzNAV4/1rZWoxeag7LT8/Y2rr0GH/lu2OsqkZE2L67/EYew30qyNpl8THSIpJQ==
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
