---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBnKoGULDXQHfpx6vD3ELqgMuyJRoXUSajle4vwD7WLYaAZct8wCWvyQt5kaKYt1MqXwtpkM7UlHgr5PkXKT9za8cDB1OOewRDbcm9M1JlxMUe4uIkex+yOIRQWPybFmPzadHT0qCVeb98gFjyvF7K7RSmag01HWkv8/uafmkY4WF2QZmgDyvPm9gDv2a6dsB+Zg92vjoLRW9ceEbWVAR9D/DzMl/0maNRVvLYirJOKYEKnc6I3SlUxlDA860CdNqnQUTkep+nGR3Fcm56NTmsGe4dZRqOccw9CYCfCKUHy22Zr+B5XHvoXg6PJCP5IkhPFuc7OwQZHfbY9w4pBm8TLxAppvoSUSikR0FFr2DbmR7A+1gMawGGgBRXWrjvPNGWsmgIWRQOA084im3uN10Wdx336Iqg0/qtDIXQYCvdFe9cBwztQxMBmlB8rFC9Gbz2dAaEp5i/3u1bEO8MsuEzYRjHRq6BwMKaT0gQ5QSRvZWrtvcrkLt8bG62Ohk6syd3b+0gB5rlzpe+7T+LlLwvG0tNb38oRi62skOgMpdBOBdqUSFYzYBN5zHT/L/cZcNzEK1TKbBm7GGdNvkeYj9qe9iwTBD3HooB0uugWY2StIsBX1bCwxTAXfg033+edTjNqpZ7Ga1LmRhfqv4I4xyE4ynGgHZXIRgywqkEi8mxu+NXjMC2qASmtrTOBdFRmdC/zCJbBsacLrBJyqVDvGFuC6w==
    client_secret: AgBFUnfJjwmC/4UFtht23/8ATJ9C3SmS/z6QBZg64T0rD8pR29oIz07g5PBgxy9ENYXgeuML8b4BOYfXqHxQQEdVUmNOnjA59iJie7/6cHnvvm5/mNbf15CyuxACw59oepK7sZ11sSn5j+A9bN+jcunX4WPiNs/5BzHjycPL1aM2S3s3PMC90VGN0Q0gTiNFdpMtIOIg0x5HKMgiKh36KgC42WeLSV1X7mjOaOTuNIQ4iYJ8Oz5vLlwuL2BAKA4NcurGk8rsYhJR0J6sLJG6X5HP26rE29hAmyMCoRAHfcRbSquht29u7M1OGXWbVNbXu0GyoOKs7JBt2BGyqjRd6yfds3N8TMpUM73SV671ZdEtRIWYx7GvEIIDBLKuSyEHtJnTOvNv5KizP030p1+iJSvXCLmM5uDzlcutSAWmIuCLQuawkfO7tyuEQydXCEKv2tgCl+6t/PxbaJVZTa3At00rcn8QTVZaNETQ5N8q5cbaux/wLE+PET8LoU3WBtIS7MmFtWQcU3aX9Q0EEbN7J0qTZA6a6ThKgaIMrNcgYgGfPaefl6Q4m8LrM4IT40ixL57eD3YSL7bu6SarCkqqYw3iGXAiWkCOxyHr9PABIt6NvG0bNOLK9hNRV0N8SnH4z/m7Ai0upk1OfkJ4NBU5dWiGVtg9wIFIQT3c7ibsxsrKF4olEjaQlEZAhivSxGJn1eoWM/YL/nvMrLvWfRx3KPZ4fd5NeQEl7hgHejrmpIL0xSQaK3u/uJwWlIk9PQp7QB62KjJHGJ6PO9IAV+FtKiIi
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
