---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCU4tu6uxN4EGhBJTD2OMbki4G02xEvaqby9IfR1+Qv1FrORuF4rF+5pIZAkfhJ0ly2aihCrIGzsoLqq5Qc19kGcWFps4OuhIZf4hTM8A9rc80Ur86kd+JUCIxf+EWxb0aKEeYGVWSpt0275pgfuyu361P9K5WUV6J9JhewhvCk16CDGAEURg3no/yZPFNyDeZfVxMCz9hCZBohDJvaoeXbyRM7CJyzwBVoFNI/sNSio/8jwVjqkqdZp0bvpXmldOnhPrHmdCJV/f//k6w6Gp6ZQbi4nNgQG2fokqatfhTU8/Twx8oRNjRth2Qx3v9qa9Eza0fjYFvuYQeo4h3+6bc9wR8Xfsb/Or/LGBL59UlVo5c9C67Qyo00tBJh60qAY+7rr7ZyrHg7ISuPGIHJ4/ghfC9sl1F4avN9HPMpn4qL4MOjJDYT/qASVxzCr2S+6DlYmq9j4ZlRuj5VKwPAte9V11+E7WNcvZr2tqqfAGOIfRhSJ+eGERHZE/cWaqBrgR72gyJKDAo0nz3YUJOB//TiDFLe3MgjidqONvC1vc4XcCKp5aKGhtptlv/cLe1maiHY4oL0D/c9K8GF1hAEcIRZ4bdNY4ih/Ly4ih+i2gfKWScxR38/dHXwIk8UfiQ44Wailruj2d3WYV/RBnaTxB57LaBUHw8qDPOFFaNvIvi/yfediY4AZ6GuvqLVF5NLLaC4W+zAT1pkT1VF0QE=
    client_secret: AgA2jNohc9rEx9ZHtrFaDFIWpG8uC1zD7coVqI4flpjhHBEO81uvFUCfakIdGUi3apLuolhm6+0a+JdzK1P1vj+fKdY3Ms3dslXvj+BcQjtrcBiqSeGROy6TLyMb8JpcqXXSBJgncHnf6nLghAD8O6xUiHT1s/d0fM0vrS9AQZMW4KXsfPr/6oCyXQUf1nu5CIzzfmPLB91fuwYS00gTK0nv8l0D1E0qWJXdS1rhA/HxCV21omtkWqbaH7OTlH6DMnGB8SSTdnaave1QJdJIQKxaKLcJkkl05mZWmIkGmfyn2q/Z5Me6VMjoLlQLjYdgKpGCF8I17PcK+mE01AzTNq2qfmCqc4Vby3Lk9vhQhCI76kBw38jhynnNBJ/R8KePp2GY2GuxlnRzgwtKqMsKqH7cegMOQp/3yWBLFm+In3IaxVlDbDGt5yr0TFsSfbHrfXfcyKxxwLsMfbIkCgokOx9V+hSY3NZ8xpKiVUDpT/RNCdahdeWFX+fPGje8XeJ0nT+6gbPOJzzOSantkQMjtJvPWsGDQGs53GEdz/nsBFlWCStXFBLwpFraJyM6VsY3ULDmgWVW8NvUiar/O/R4l+5neEHI5sTz6qm3zt9EhciXxRZ/pOxPTR8xkZGHjA6d0Qbhh9ZCywVvQlYYq0RedkfIC64QqJYDS2UcwUZULvohFX3Ba8lzwO9j1sgnmssneiPmuIfU2v7HHfBOwuUdzjbQBu4iVcFyyYoESkc0SYbNXgcbW6WSmbtT0aG8ashRbUyUADn3GfDYHho//w==
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
