---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBN16z8ws0nBtla7XHYY2LtS3ktodlaFUpHNAt0OwLBmWTJHVyGQU/hVRo7vCYWHnDib9L+Hi3/q1uLWLiuG+BG7+eKJUhhDwkJWNBAXqqmTgoBGPWGSRl/Vw6/L2+ZKNDekt3md7WQJCqAJFbyjlKsJueitI/IWU6UvcKqSbNZMR7RRtr5QNr2WUCdjoop5YeXk++xABcaeQbOToRuL+v6/3Xvy2+rWabWvrsVOayFwFLLjPd3FMLLBJ33Qm4O6uxGbiQNLvqFrb1rXRpjNvBh61CCpwD/p+a3Q3iBzp7f9+TzjJ9JdKiKV5wJL3euXiCR88kZlyg778q8Ux9ahGvYY9DqzrKVZw/5Wt0DrmBK91AmswMjZx07U3w3gndOmn1zWokOy9YVYaK8FFIOYWK1t1GRJFxsKUpFpM53x0G18sM7I1BmeluY0uoxM7P+TDrB+6TcIjWYXFCciYy+5fFl7n6k2/DrpnJFJunIQ8gFdOXB6lDdni1DuMy7yIgWZ1z1K0Esnmb2fSUfymCU7mk1g4+B4HhQRiv8qHV2loIxFdbxnjXIKX56MHWxg/iUXtEBKmPkqgymq8omDVtbhPkJMLiltMpM8y0NMRfo+o5hjvHDAXfgDJAQNOzYVYicg0pSpulMkqo8wdhF01FOihMURahLjXhoDaBStCe2Yrl/FEEJGcoKFXt0TgIhZIeOexmxiOYlEM5UChrepTcC7uUocg==
    client_secret: AgAEHttU2l8FD9rxuNW41mbhRCB3jVoiMQYLOKOaeE6mfWF562Y9QszGBYuJVTGm+UeBZqh9U83+9rNgM6WwhqTll+aZAQ9e7fWq5rrkNmbNELmHJ3tl3gi54zHQC8U1Gs4KaXL63KKpFkxUbMGUmbQum9U8oYWL1zLI7SX9VgyIGA0GFZH1PIsPwfc3g6FxyCREC6xVHdR8ENHQjnwoaQGEsQXQSiRI/mmJm5/VX4FPtFsDK61uSeN6dNcTyrhZUJNHy6EKpwAOn4+tY/tyz+57Spqw3hv9bmcAbAvgiiyfw9QLFISjKR+qWzd/CRvehthONRS16jAsoCDqIrnoOE0M4Wd+fX/f+/lyxqGZyhVMy6oYkDkuHqE9Y+/t+FGjwaTiHnB8zxG8ixl8b1b3AWFSQIByBU83z0Wtj49NeTAtiuqzNKe1mavF8vWAk/6GPUpz+E+F0pn72Ytns2E/1uHiLYfiI5gd2241xosQuhqwDgQ0RCPORyj+yuJb+G0uKPOy50cZ8xOQk9DwF6wUk0y6oyqC2DTohV9CuEV9zVdrdbhET211Zrk6REm3jey3BJcRljnrf9O9lyM8y3tc8bIe27J1fpZHfbTDC92u9YqQq7yJaolZWn96X0M9ewIbr/e0fd14/kcZOeX5U6aqoBSD22FlQzsA38gIYFxvRuWxVibxAcFRhEWM3MctviV26ApdEldK2QuGj7uXB3kmg1gafckujbABL/5NstLIIsDjxO4LUNw5EO7kq5W0oeLHNX8a5hQ5EDv+2pPJ8ChfVlEE
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
