---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-postgres-user
  namespace: default
spec:
  encryptedData:
    password: AgCEmuXEasnH4JGxECHf1OpEHFXxvPrpXPujHvaXDBwgXibsyjRY1o4k7uDNkxVna1QJaeMIPea+rW74VOjIveTe3Rq88GFTExajCQZNAA5ATcy3heigqO5gmgyxn48AdQp0r6kPtZwOMvTJZMYXE3ImTGjrAy1AOwJ5q1nHfbIuL2LcN19/zudB4Rthx7SpnAl0kEkzRXCQIJjMOrafWY/O8YzEgfqF2pOLT1xiW8hdbK0MhzPMMjximoeTchcXu4wuBic16KxvYKZv6xcbxMgWdPIBWQkgspmmxwG54xryAPjTNJ1QYROvLTokgsijxl0kPyCZFk0pouj/lAqeAwfBVgZ1q8fjcRV8Kk7ft6vSunY8tpQUehq76a+/rYMKjnJOPCwrejSH4LaLOAYnJQWaqofQuj++ce4kZ9kK4o+sea0W1vfAdZE8PaMn1saiZwOYfbSnEVsv/e/EwrIXoEG23VAr7b2NnWEA3qafHqMvg6v1yoo+UjhW8egUyp8egxHWqLhovMYkmeDcklCej1xUPiui+0y5XzUlPUIzt+Bn6d+tR9gHvKi1dBPI+IQMGUBIPqTF5g8ZfhbB8YIu2pm9DUZFbBjZfPj2uRRJPJTlvfaF+CZ0QO+ApMIiNe/yOHN9inwWt0nQqxWHRtGmVCiJK6aqhWF8t40QJsJavxtadG/71jTqESskhX6GEziijLBg4rHvTMe8+XAs7ZFzmlmoco7/yfeBItkl28WLa/I=
    username: AgCegC54V0rxlQN6fUkZr36CMspo8LPnKUJhwbYY18bFEQEVwW0alH27Bq94YyWXyCvisBqJJyvhcNzr9cctJVBdUJnMO0TQLBfXX+7z9w+lvCUVlTB7a6iogq0G/TxuWPnzulfFaxhktRw4+p510cPHYGIZBaOUwnAiJjm05sy0ou1bnXpFZJheRabQFQhmcKBvHthgaAIJz+ce7iOj2TVyOo1Wr1y4DC1Dj4TqII0yr0a06FTMHQ+HlxwykNaFmE+mAYqTZuGRJsTBhJIHSqmxxLWaGai/5WL0YeJ3TeV3G5TCTStVJSZGt5aqdcR2PsnobcmaCw3KD2/2oYz4iv9E394dOklElg4YXvJ3LrwCN04wRXpzCJQakPm/GTrLO7dtHcgZTo1WRcs9slVvyadE9IF/Yr1AO7gS2Etkkbe1OXW9jmXhXRFzJBZX3NJmgN7j02/oJ0QgVY03hVE4V3AxiyxYOEW5lh+ajzGeyyOV/E3s5hLp+LhywDyiOhOy4EWfoQ/4Sr5sjMQra7RwS6DoXqdwG9IVkijVOKxFvQtuVahI2YAFCJcLE1lUL4z4nqOOcSYwFqhE8+zhSmv7AipFm5kS2jamUaoue880p/6BLTji+rjZ1KoWbPBvUu75snP5qk9iDdtAm3UC5f7rwEC99XjZ+yq8NxzVJoYPC8ADBLe1m0rbtODKQoeTxNJ1LYtDCl/RCTU=
  template:
    metadata:
      creationTimestamp: null
      name: immich-postgres-user
      namespace: default
    type: kubernetes.io/basic-auth
