---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-postgres-user
  namespace: postgres
spec:
  encryptedData:
    password: AgBC7VMa5stvd/c9wyuD03DLpf7Q5wJ9u9Q4cX1Xi1QLwhF2js2HlkBfvyig7B2KDjowwN/OmDwOkgqMhDELJyCNaWL1MbhZ7I0PwuFQqq/CTpMFaBoU6EqfOMTD7Ctp6MfF+EyfLv9L3LCoC1CZTguBhDszKoB+mZiXTaHyk7J04Tm/nEThg/W0AQOKUwbPBLNHC/S3BH4ASEppKRLvgMl6I08m56aN1QFqyqgykkWfU+We2WqYe1HhR/G0lcHDPTyq6G6oDQMO1mz+60bp/ZDgcv1bySvSEMu+MIjLSBGmDotfdkg1Uwk0asc5ei/27bcJWyxvPZY3+g7maFp9lyulG9JNgyZht0PrMpFunw/+9Vwpe+ePAmxTgy0RbssuxKrT35dc176uq+2Wvwms5xgfwif2Z5ieVKaxZ9Jo1Li5WXD8IIMIWYj1b0vbbPnCSz4qicdpqzgFjVma8zQOIMEEtn3sN8DFww4d89SrvQQzgfZOUkksY1VwdLKxGA8gW81VEzjg27Q1jA5h3O2OVPlHKqbNlu4oBxD0YIwXl779zXGh96/X066cwhG8EQlix/nasHTLe+7EQgl0S6DzwkTC6uOAkmJ/UVopMZ6luBbO7VXyiXQj9xc3lx7KmOGHhGTBZoY5lTVGpfFlA5vt69yiWbzhWAUt8cpsshSisNEBMts+w31WNWbvR/pmniiP7ulUZ6t1gVBRZQJH/cxOkfHmjpuCaOOOr69qfKSn3nQ=
    username: AgAQhnvlZ1oc5E9hA8M3Swl/lLFpxXPxP7HT3Mq0hprtkKSOY2A8OlHm2CucLJjTZ3lZCYpN/RH2nfM6PV6QJr4ePUW/gEIoQtds6FsdK5t9wV+ngSXfKsNUzZSJfqBcjM2S033IsF6cBVrIcq+3M6Jgz6jFIR/XN4tI8rjEPMIEJvDRqSXXIZgA+aMRe5l7FU6YAU51Nn+keH6kG/JAzlz/9rw+N2opYBvXro2w39XyptrmZdHvtSTWHasQTk700Tzlhrl9disV/qGADCu2ZXBIIq5zdm8GkLoo1LQUuEsv/JxF8Nw9Nvo3ulGHq5K2rlz020/cNw6no3RQ0Ng+UEWkXpEwAuiEdkT2evuO7huRYp6/S1GiWRdP4mqEcR/GyZCihuFgj61eIMInnNiZSbKjnZjHv65IIyn6Ho1cvt3j2sz2ZVSmbVM5jqzv4RukrU9m/aTFWWszQ8ATrfaUmOTkgNX4svcwpwQOg+GkaAe4S2kfo7JDTr8bmiM77DnXdVqmftg6owWaEeCc+MRNkX8rrShZ2h9wVSVPSb9GPzYNRgrFGS/msmnOVtLgThaByQ0e67aLQ/FrNg5UT8IIP+DxQD1v8X67I1VQVsMhmimAt239shEVpey9t33li7lOgMVXGQe4iGvuo9fzYrLumFIvUleKPvVEUmlLwnPA5UASQxHvB1GKP/VwZlw3kiy+FzxXNrk/tV4=
  template:
    metadata:
      creationTimestamp: null
      name: immich-postgres-user
      namespace: postgres
    type: kubernetes.io/basic-auth
