apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/releases/cnpg-1.28.0-rc1.yaml
  - image-catalog.yaml
  - namespace.yaml
  - main.yaml
  - route.yaml
  - databases
