apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: main-psql
spec:
  instances: 1
  # TODO switch to extensions once ready
  # https://github.com/cloudnative-pg/postgres-extensions-containers/pull/1
  # Also immich is stupid and does not yet support vectorchord v1.0.0
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.1-0.4.3
  # imageCatalogRef:
  #   apiGroup: postgresql.cnpg.io
  #   kind: ClusterImageCatalog
  #   name: postgresql
  #   major: 18
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: freenas-iscsi-csi
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  #   extensions:
  #     - name: vectorchord
  #       image:
  #         reference: ghcr.io/tensorchord/cloudnative-vectorchord:18.1
  managed:
    roles:
    - name: immich
      ensure: present
      createdb: true
      login: true
      passwordSecret:
        name: immich-postgres-user
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: main-psql-pool
spec:
  cluster:
    name: main-psql

  instances: 1
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
