apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-tailscale
spec:
  defaultBackend:
    service:
      name: plex
      port:
        name: tailscale
  ingressClassName: tailscale
  tls:
  - hosts:
    - plex
