apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: filestash
  name: filestash
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: filestash
  template:
    metadata:
      labels:
        app: filestash
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: nfs-filestash-config
          persistentVolumeClaim:
            claimName: filestash-iscsi
        # - name: nfs-filestash-shows
        #   nfs:
        #     server: 192.168.1.112
        #     path: /mnt/main_pool/private/media/shows
        #     readOnly: false
        # - name: nfs-filestash-movies
        #   nfs:
        #     server: 192.168.1.112
        #     path: /mnt/main_pool/private/media/movies
        #     readOnly: false
      containers:
      - image: machines/filestash
        imagePullPolicy: Always
        name: filestash
        ports:
        - containerPort: 8334
          protocol: TCP
        volumeMounts:
        - mountPath: /app/data/state/
          name: nfs-filestash-config
