apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  labels:
    app: filebrowser
spec:
  ports:
    - port: 80
      name: default
      targetPort: 80
      protocol: TCP
    - port: 80
      name: tailscale
      targetPort: 80
      protocol: TCP
  selector:
    app: filebrowser
