apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snipeit-tailscale
  namespace: snipeit
spec:
  defaultBackend:
    service:
      name: snipeit
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
      - snipeit
