apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: filebrowser
  name: filebrowser
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: filebrowser-config
          persistentVolumeClaim:
            claimName: filebrowser-iscsi
        - name: nfs-filebrowser-shows
          nfs:
            server: 192.168.1.112
            path: /mnt/main_pool/private/media/shows
            readOnly: false
        - name: nfs-filebrowser-movies
          nfs:
            server: 192.168.1.112
            path: /mnt/main_pool/private/media/movies
            readOnly: false
        - name: nfs-filebrowser-ebooks
          nfs:
            server: 192.168.1.112
            path: /mnt/main_pool/private/media/ebooks
            readOnly: false
        - name: conf
          configMap:
            name: filebrowser-config
            items:
              - key: settings.json
                path: .filebrowser.json
      containers:
        - image:  filebrowser/filebrowser
          imagePullPolicy: Always
          name: filebrowser
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /.filebrowser.json
              subPath: .filebrowser.json
              name: conf
            - mountPath: /config
              name: filebrowser-config
            - mountPath: /data/shows
              name: nfs-filebrowser-shows
              readOnly: false
            - mountPath: /data/movies
              name: nfs-filebrowser-movies
              readOnly: false
            - mountPath: /data/ebooks
              name: nfs-filebrowser-ebooks
              readOnly: false
