# kustomization.yml
namespace: filebrowser

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- tailscale.yaml
- pvc.yaml

configMapGenerator:
  - name: filebrowser-config
    files:
      - settings.json
