apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filebrowser-tailscale
spec:
  defaultBackend:
    service:
      name: filebrowser
      port:
        number: 80
  ingressClassName: tailscale-disabled
  tls:
  - hosts:
    - filebrowser
