apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/metallb/metallb/config/frr?ref=v0.15.2
  - bgp-peer.yaml
  - pool.yaml
  - advertisement.yaml
  # Why is this needed ?
  - namespace.yaml

patches:
  - path: namespace-patch.yaml
