apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goldilocks-tailscale
  namespace: goldilocks
spec:
  defaultBackend:
    service:
      name: goldilocks-dashboard
      port:
        name: http
  ingressClassName: tailscale
  tls:
  - hosts:
    - goldilocks
