apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
spec:
  defaultBackend:
    service:
      name: minio
      port:
        number: 443
  ingressClassName: tailscale
  tls:
  - hosts:
    - minio
