apiVersion: v2
name: Grafana
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
dependencies:
- name: kube-prometheus-stack
  version: 61.3.1
  repository: https://prometheus-community.github.io/helm-charts
