kube-prometheus-stack:
  cleanPrometheusOperatorObjectNames: true
  alertmanager:
    enabled: true
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: freenas-iscsi-csi
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi

  grafana:
    sidecar:
      dashboards:
        provider:
          folder: kubernetes
    adminPassword: admin
    persistence:
      type: pvc
      enabled: true
      storageClassName: freenas-iscsi-csi
      accessModes:
        - ReadWriteOnce
      size: 10Gi
  # grafana.additionalDataSources:
  # - name: prometheus-sample
  #   access: proxy
  #   basicAuth: true
  #   basicAuthPassword: pass
  #   basicAuthUser: daco
  #   editable: false
  #   jsonData:
  #       tlsSkipVerify: true
  #   orgId: 1
  #   type: prometheus
  #   url: https://{{ printf "%s-prometheus.svc" .Release.Name }}:9090
  #   version: 1
  
  # prometheusOperator.resources
    # limits:
    #   cpu: 200m
    #   memory: 200Mi
    # requests:
    #   cpu: 100m
    #   memory: 100Mi
    
  # prometheusOperator.admissionWebhooks.deployment.resources:
    # limits:
    #   cpu: 200m
    #   memory: 200Mi
    # requests:
    #   cpu: 100m
    #   memory: 100Mi
    
  prometheus:
    prometheusSpec:
      retention: 10d
      serviceMonitorSelectorNilUsesHelmValues: false
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: freenas-iscsi-csi
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 100Gi
      additionalScrapeConfigs:
        - job_name: nas
          scheme: http
          static_configs:
            - targets:
                - "192.168.1.112:9108"
        - job_name: polar-bear
          scheme: http
          static_configs:
            - targets:
                - "192.168.1.19:40001"
        - job_name: ups
          scrape_interval: 10s
          scheme: http
          metrics_path: /ups_metrics
          params:
            ups: [ "serverups" ]
          static_configs:
            - targets:
                - "192.168.1.19:40002"

  # prometheus.prometheusSpec.resources
    # limits:
    #   cpu: 200m
    #   memory: 200Mi
    # requests:
    #   cpu: 100m
    #   memory: 100Mi
