apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels:
    app: prowlarr
spec:
  ports:
    - port: 9696
      name: default
      targetPort: 9696
      protocol: TCP
    - port: 80
      name: tailscale
      targetPort: 9696
      protocol: TCP
  selector:
    app: prowlarr
