apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr-tailscale
spec:
  defaultBackend:
    service:
      name: prowlarr
      port:
        name: tailscale
  ingressClassName: tailscale
  tls:
  - hosts:
    - prowlarr
