immich:
  immich:
    persistence:
      library:
        existingClaim: nfs-pvc
  controllers:
    main:
      containers:
        main:
          image:
            tag: v2.3.1
  valkey:
    enabled: true
  server:
    enabled: true
    controllers:
      main:
        containers:
          main:
            envFrom:
              - secretRef:
                  name: immich-postgres-password
            env:
              - name: DB_DATABASE_NAME
                value: immich
              - name: DB_HOSTNAME
                value: main-psql-pool.postgres.svc.cluster.local
              - name: DB_PORT
                value: 5432
              - name: DB_USERNAME
                value: immich
  machine-learning:
    enabled: true
