gitea:
  valkey-cluster:
    enabled: false
  valkey:
    enabled: false
  postgresql:
    enabled: false
  postgresql-ha:
    enabled: false

  persistence:
    enabled: false

  gitea:
    config:
      database:
        DB_TYPE: sqlite3
      session:
        PROVIDER: memory
      cache:
        ADAPTER: memory
      queue:
        TYPE: level
