apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
namespace: kavita

resources:
- deployment.yaml
- service.yaml
- namespace.yaml
- ingress.yaml
- pv.yaml
- pvc-config.yaml
- pvc-media.yaml
