apiVersion: v1
kind: PersistentVolume
metadata:
  name: kavita-media-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.112
    path: "/mnt/main_pool/private/media/ebooks"
  mountOptions:
    - nfsvers=4.2
