apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-media-pv
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: kavita-media-pv
