apiVersion: v1
kind: Service
metadata:
  name: kavita
  labels:
    app: kavita
spec:
  ports:
    - port: 5000
      name: default
      targetPort: 5000
      protocol: TCP
    - port: 80
      name: tailscale
      targetPort: 5000
      protocol: TCP
  selector:
    app: kavita
