kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-iscsi
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-iscsi-csi"
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  volumeName: pvc-a1be0bd4-acf3-4b17-90f5-92fdc16e838f
  resources:
    requests:
      storage: 1Gi
