apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr-tailscale
spec:
  defaultBackend:
    service:
      name: radarr
      port:
        name: tailscale
  ingressClassName: tailscale-disabled
  tls:
  - hosts:
    - radarr
