apiVersion: valkey.io/v1alpha1
kind: ValkeyCluster
metadata:
  name: valkey-cluster
spec:
  shards: 1
  replicas: 0
  users:
    - name: root
      enabled: true
      passwordSecret:
        name: valkey-cluster-users
        keys: [root]
      commands:
        allow: ["@admin"]
    - name: github
      enabled: true
      passwordSecret:
        name: valkey-cluster-users
        keys:
          - github
      commands:
        allow:
          - "@read"
          - "@write"
          - "@transaction"
          - "@dangerous"
          - "@connection"
          - "@scripting"
          - "@set"
      keys:
        readWrite: ["*"]
