---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: valkey-cluster-users
  namespace: valkey
spec:
  encryptedData:
    github: AgBBSAh0tfu4Ixcnaz9aKyzIZEsQK4QS8cBuSSd60xOfO19PkuqvND3om55jEX/hOSoOdL5TAHYms00OcjSSRXsD4CicwbLs+vRUV+DlGQr7L37DbcrQl3/5WEuMSegVWKH3g26ngPlvm0ZX66lrQuRAIolenlP76JYFe1TomwqtfOLbBSe9kRGJezqfPpEgCAKFvia0Ep/V+RYlIwden7nsFlyB+GqTNtKyEaZXncydv7VSHjljl+lm3DltiLUgx/4DPJQyvrHpL7twOSOM1fe6SX6YjkHxOJWWSpgeDCAQtcODlZe5kDEydrHzgKxm3Kwa8kFTGamGe0SR4PH791OTgrmLDUYAgXRp8r0K7E7VuAsk5J7BMkTPTLOzHRAQYfjQqxuKOL4OD5WK1z2q8gNXvGAA9jaPlokhRNHkFyTPErM0Tzmlqa+2QVuQKCP5NELKIMAIRh6TVaFY1w7CspRGV9sTdRR8OEbE/h+SiH/3Qg+uecEm/uMykLc+y35NFFVX6yjsfiaFuPzYtiFc9DC8/MCpi1FmrPQM7bDQlJlFCQjC1jaTt2G2K1bcAgAAViZhWJwNjbGyQezXLM/43XbxOezi9h1odaTz/xNbEkcewbWPmljZjAH11fP5+fTSNTniLL5eSQZJjP3Pl5z0AP56mN4+N2p4VztnqQxQ8M6JzyLVnE7m/WnzOByTnJBVDjVxqqEHaSN6ZoSTOE2dBjbJZ0cFy053Eok=
    root: AgATkCuANqsbsgnMCIVo6PfEYoTENKpaz/4J7MQdIc9KxNoZD55DI0AMiwnu1xOwVUNPw+q1QsVgUldYxkOhdIidXVaui2ouL3dpZb3e+PEPchi+hGahaEqiVYa8jgAvx861vguiH/pSD8tewhub7qEyKJ5vQqdDm2+aj8PC71L7ShgfZ0kQGlaCB0OG71iL0D51TDt4rg7pKMajKBIrt5op5FYybbK09a1egFYYdq58WPJeuY5RBPB6Q0Bx/JKgf3O7hqzFaUpF5kTpb0NKDFJpYQHiBfalWK+Mm3SGresL/LSDuXKc+LSyYed+LgZSyMB/7yLD2nVgYLJ4eVwGV3gsdVj+m6qE4qkPbFXYA2fPEBO8LznaT0Ea51vDAyUT7gPkapeY0lHrx7nFL4st2Sn5TCkOrtjjIRsyThIeyjB0eFSvhBBtIgXH0gOdfdu4Txe5Dw/29KYcSBt/bAx5yypLWj2McBr2tQ9inTJLPPcyyqw0k+VH8xXQCWBFa9zhYIbjKARHn3X5s0CxL9uXdRACVN0Zxs1TMQVpb8KCMjWdjFVd9fKY1OdCvt6iHJ7A8vfRqBYTF+7l3WdhFU+krTgz1/siB3odsAibDXtXkFAXUOIp10yItEoSskqTMn6ppzHR0bxV+nf9gtLSM5sk0JalqWNRi//Yperl9fNXcxC4C6UzZvs3CMxaKWmlUcI4W05UA2rO/EsPh4Vd/7dHg+7keefCZS1Tpas=
  template:
    metadata:
      creationTimestamp: null
      name: valkey-cluster-users
      namespace: valkey
