---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: valkey-cluster-users
  namespace: valkey
spec:
  encryptedData:
    github: AgB4tlwFSJhw5hqmqYiDDalX5B1ZHzH/ByoC4EhZNHgf2pqbRiRQMS8JtWPtYZjZ/ZWwEZzy7BQHfbtxwX5KL+14J4FWZt8LN59lf1uaDjFr5Z/feQVAi+81p0ZfqIrOcLddy9AjM1+Wf23wq68uhS3jNzKESgExQT/KapNr91Saztpdh1Hte9RS7SVlDvrYOM7U/HS99g3F8wENtO0MQfYPyVRw2lsHW6PNmY8aqeuLuQTW+VUOGLftGwCH+0HGYQ3oXGqKhNOBheu/exJdltNh8il4wmMENWG0mAa0ZLkDqmB+Fz6tVcIeO21APf0lyAovrvV+cSefVOanMvWErKeHQFh0RNRgGSHPzJXSZ3QuT5NBWbRMbMVuZW+QhcCbCRKBARpsDFfKmatxjFAYHYsS6uHGcwXibADEMhzyQTGAxRAmOY/MESc7gnLx/LwhElpFzWTS9e3EvIfgpV/FfDicA9M+A6DRnRaloXYt1KVSXmg6uINfmbssWm7jeupHvTb4b/TldDwSxMa25q6PztMuQ7nn7hb4PixTytADfFJ5o389YsMjRfv5qWeprenpS9PhlX9oxCUBLGA1wrWCApEctLVigoilJ4qQBiaYjqL9/ZjR0as9vyI8CV/l6l/imOlRbQpS64rqP1LIoRC8UlhS0HX6fffB5t9CGdbUbNmwDeA+xKn+L2XegXaJquSv505riycLVH6mYvP1B3dNE4StFiffceNKcjXM1P4WeCTgXw==
    root: AgCI/xJvbdnftygFeLu4b4zUDzBLV0SW6vpGai7HCdqVInje1V7fD2wlaKHQsYbk9UcpxcsOXuaPWl0c6rtjtmJuYmxItrEboR++UDrApkkpEtsPi6sUSd+0CG/Qek61pMXo4D9KUnQTg6WfNkksNhE0t+OqfB0P4nuNUmSoInqPd7zltFqF1fTMEmtad6ZhkEf2Hv6RXpLVTZzt8+fyPKnFDz6Ixlh21psdtja6hiGaVY7VUx7NIxpWEXBcHgyHVa6U6W9sgtHDuEuUgBp0ukp/BGJHKeU5qpYZfziYjZZ6IevXlwdu8Djq1UMa+RNuoIRiMcA74O9FOI3k4P+oKUEx7odst8RSUuW+QkU5JZ+Qw33KnjJ1yajNfnlvTAtzJU1OiW1Whd9F43V7iXkoDf0f3v60/xOU3pqtmHidyo6Rdh+kSmRjpSKaw5ezHhVCyCdD792BE0Kk1WXx2XsC6kP43bHJnZNFl3Hndrp+jhBvB6SznT2Ml8rpC9trXzDoJIYVqeOU+PIUlKrCuZF/al7nsHzj5CVtdq5IXnU9bLp2PbQKaXd/zmcJw/5xH4PtyOCgO4ilpngtd6EW4ui9T0BdG8TZT3qPaEmMMf3I0XUkYrx3emcTNGbk4rNjVnyrj1Gg6izDu7Jisykg1/LgfOuZsHsbYxkzBewe+mM13zRxXmlbsn0uYZ3+Lwpg+5Y4RZaGSSum0DvSSVM7q/EW0aOU9/Qd523c1dbuP8EWTMxq4Q==
  template:
    metadata:
      creationTimestamp: null
      name: valkey-cluster-users
      namespace: valkey
