apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr
  labels:
    app: readarr
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: readarr
  template:
    metadata:
      labels:
        app: readarr
    spec:
      volumes:
        - name: readarr-config
          persistentVolumeClaim:
            claimName: readarr-iscsi
            readOnly: false
        - name: readarr-media
          nfs:
            server: 192.168.1.112
            path: /mnt/main_pool/private/media/ebooks
            readOnly: false
        - name: readarr-downloads
          nfs:
            server: 192.168.1.112
            path: /mnt/main_pool/private/downloads
            readOnly: false
      containers:
        - name: readarr
          # TODO maybe change image
          image: ghcr.io/onedr0p/readarr-develop:rolling
          command:   
          ports:
            - containerPort: 8787
          volumeMounts:
            - mountPath: /config
              name: readarr-config
              subPath: readarr
              readonly: false
            - mountPath: /downloads
              name: readarr-downloads
              readonly: false
            - mountPath: /ebooks/
              name: readarr-media
              readonly: false
