apiVersion: v1
kind: Service
metadata:
  name: readarr
  labels:
    app: readarr
spec:
  ports:
    - port: 8787
      name: default
      targetPort: 8787
      protocol: TCP
    - port: 80
      name: tailscale
      targetPort: 8787
      protocol: TCP
  selector:
    app: readarr
