apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - prowlarr-secret.yaml

configMapGenerator:
  - name: prowlarr-config
    files:
      - config.xml
