---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prowlarr-postgres-user
  namespace: media
spec:
  encryptedData:
    password: AgC1Y0f9P6bE0y4LZIV8rTmiUVKJCeLNviYMipS6vgzfuYTjQId+YnRDOxZinPu0g7wHEYzCB7JfYyZVQPuSqnYZPh8E4j5YsCDmhjcXy2TKKS5nNT8ZKLG/aiYDHniDVCQ+iBFWcEWG9dALpGMKhhIezm0IjVuwQP883Hz9IjqwJfVHpuru+lVAVt9TJ6taHBYQ/lLx0x2O0y9xNIn3u3EqiN8l1zd+ZMwiQODRDeOOESNlpqGDOaup1K2G6MfXaXB/F1NbS4xi6n71v8ajnayacnfQQlthyI+JhEcb46uUqvHFzlgK6BIvXz8THwAxb7/iPpoIuJewrtMwg6/2rEwm2ZEMH+9k8K3veeEPDViLJfHf86xVI4fDBQVQyThV1RhQFKswt4KDBgQG06IM/5FnFX7ruvwV3SHK+y03PXgRJvorXfU5INROd/IW5UuXw9lQw99/tbNgXXEvKH6WQfWbCvyQGIWkV5dPYHbQJKivT2anSlaQ3BQzbMX+iNA2KzoNie9+QfafbcmUIZnveDPKRPoshfqd3PkzOOZ8gDeFpNX5aA3OzeUFBbr2XFIPtH16NBceq5Ep1tSNHJBQBGBLcQ0gUUyfX+LZBg3xw7GAht03Xai1YVIrswHq1V6uGECJTxilo0fmFF7aP78MTNhBUegb458C57qnr+7d3ZEsFx9AqPCjUOS2ap42GofIWPP1mUdnhkKU9w6qlAZcuv7I5SDiYGBxwZhEWwQ5nSs=
    username: AgAaULsq5Kn1vVt/CgYgfD/p5eP3sD4zZlTn5k2kCvRAXKaqYELcHgKivXjchn2Qc/zi4fv3xt/unSAHfHFln4b7VhtoUsK9kF+myl2PDzbJissk07f2MQcsBKCO82RKvly7GgkGkIy3wLSXWL3Ef+IkhcFvCyQT90ld3Rqth86otzSVvZ0iYfoUD0HO30HN6CTS+sTr1B8V2oahbVEHlNbMxyzVYtjoFWLpU2V07Z92o81HBKf0Gtd6MOvga4APWBE61qVQekvM5FvpSL2Z4SUAVr7kLA/Xl3z9RYckwwwz4LcHfTbSVopb8cvPNorrjMlTp+5RWgEtBMrbCplkTTvoi8XnkwadMd5kMx6VLIPa/MMT3rDFOBOZAmnYNABNDQ9rvZC/r4rvUSTwD4j4Gp9Kwi2V3flObT+iQuXjBL4pnUJK2x93NO6/PhzdvuL4pa5x8TvRUzLh0WlIBxy7KUwSAdh3R9v1n0GrUG2m590IobVra4L0EYfCljxhZ3Jo3TOOg5Y1LOfgTWPr4UkncVzPgGebiGsU3jAdhwgcPb5DaNqglh72UhtY462yaxQlDfNouhQLUsdJRPdWeUU/zEn08rfScwLHi8wPcrdfhjG4PMy1YX2ArSaKHUySghwyF479J1Fw3nYs4iJRXReX79cvHrC9r+IFwmm2zy704FECXgGfU3gj8yv/bHaBeRyI/ZwzR2KfF9chqA==
  template:
    metadata:
      creationTimestamp: null
      name: prowlarr-postgres-user
      namespace: media
    type: kubernetes.io/basic-auth
