---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prowlarr-postgres-user
  namespace: media
spec:
  encryptedData:
    PROWLARR__POSTGRES__PASSWORD: AgBHJPiD24b5fycpe1D165CveEckdD6eJJS798uvA2cqRrbunG5YEwZVUWYOpaxPjeA64VNQFv4VbFZubFl1G40xZQUT+LAu+s7nbzKSQwM6xKeE/ZhtJHXlcCGe7EVPZoGgmYFOy6w9ARFf3661mgDBxOha3g2Dwds9yyteLJlzTcXgB+FOcJrvIqYE/BEqPwdn+yQA1sw1KutgiNFlR3lsG+XOGqswXFMhijnIim+5qk/7rUlKi0Yw81+VtzS/iq2BzjvOhsQTTeyKg5Kylkgk9fb/9Yak+54yiWdI0heTUDh2Hubcn6Wv4NrLef3YnodKGWOKG071VgR/XsO46X7lj1qpVIlVW+872DL4irlA0vB7n9qCFAh3aBqyG71Ml2E2UmybtGMYv3hQtqh85RtPIzuFDMO+cmtHF1e2L/G34BObO1pVEpQrU3Jz0AMmsfujNe6798vgHqb/yt+h21V5lGIOyhSnc0dLztYo+spsXz8+NS/i21BRX661AYRh7z6mbuek0wkWDw1l1s4jYsBJMdCZ71RJHz++ieIpLh6No/OPPXydCXvjOm/LAy1TgtGiE5pjIacGQORqt4fg5isqaHEgQOyiwHTsR4JgSfUs0lORueJTrGHyY/iKJBgRkNSXLkxxVVHceJq4kNxmMz/Df1z/XnKbu+GMolWaVVJMbhvi3QNp4brzZ9eTs7JgBy3X/aLq3ueVyZjph5ZyiTEraGkPVH68GcEsWty3Bzo=
  template:
    metadata:
      creationTimestamp: null
      name: prowlarr-postgres-user
      namespace: media
