---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prowlarr-postgres-user
  namespace: postgres
spec:
  encryptedData:
    password: AgByNu+gaiLdpNqxJlRU9z5U7fJU9j+9X9wKHptBW2B2zm/e9gNXdPhOUAb8ftUJiXJWP4q5zm7YmQA5i7SBKUNt2uvbvBdj6deZRVaWmShJnwfchFTYaxxANrokvLTkyizuly2Z7ZagbGGGBTN5IA7IYZ9AvfROpkCxCsK90rzN6LYIBsAvovN1bRnnoZbzJS6+XJ7xJquUIY3nlNs0z2chMVFE0FhnPxF+ODyA/QjiyGQRg4hqMlpW6PzZMd9ha0aijZrjYsZLpZ1fM/ETUXNABT5PzyS+YpbmWkPZXRWRIn+Gz7PtlX/42OzRFbg0T7Z16/jQmusxjEJdwNaYUk7ssDCKU0FjTxWOqGkw3QZHAhuhVtbDZPrDU0f6Nt76qP4pCecSbKPYww5XeDB/NPDGkt02On8WG9lPz9+mzELAXCRfCsosRlmuU7S+oqpQWL8FXPNTymKGtnnT3Tz3MJwNeO51fIMrSTohs4Da6x2Wx9Z/ysD7fSFp5wnemudUBMsYtzG8gDeATUmQBJcCyN3n04nipykWDUMrVm+5x1WqmVO1V16MyM+9kLLLz64UMrevt+TzRHfkTzv/IPqC6kdvB1bP5IOyNJw7+GVJN9oaIuvD8M4nZqiCwUacNG78sxnoto2HDJe/lpEZFsGSO85dM4WfEEde48dixL0B6CGeVVo1OoGYOyP2HDM2F92iDRUXjggNkwoG15qk711cA4DLZrp68PzSiMkWJXcupUI=
    username: AgBj8wJ18lo6iZGQpv0Mw1ldmdkZw6as0MgOzXGUa5QaDIfJY9nMNFZqSSjJN26iMzuVoyNpu7WEDiiEgJnzCxunkAepqP9MIvzPoFNe6L7q9z/uVekty6zq6dbKVfUpqfv8udCMtMFL3kBGOku4baW7wqibV7b5OrLvnn8wpaGZc1U4a1wzTXdlDaxwl9mpYrtU+iL7le/5gwJGEHQS3a52pQBuYicgxZ52Iz4d9c61Coz/mQ+GfER3Bc7JjU8RIGHm54O+VrvPp9M0czVT4CErVb9re0RvvEVr9XG/i/SblXHf1FNCyn/pAd82LPlHMgph3lhx5ct28De/KGGJyyYUVrAN2QA92TmimEdAAt5BnDV1CzkXpg0VqBkrXdIYKRN4YBN1Oj01NUnAgopxJ+cQXD8iNxjfhfKkZX2z+pmdPPpPisXzH0FqiSxq2AqsGNaoPdns9A5n2Qg3Z8d4w1iqqrj5cGQJnGQPmIPovVl5NOPgnOJuzH+2ej2iMdttDax95RYc+qvyKmt2nBA4XKsWes7cZJEcUbMIfbtkH4EVBkDH/yctzS7sl8R7jUlZunEzIrxCxIE9IyvD6bAB466V5u6vbB+urR0KaYx3KxSfYaiT7jVV4rWHxPYcEIYLaleg65Df3H2vTgQ7TVbIhlz49DNgAJY5HPQVpz3RuJGEU22O/znCD5+7S0EvFB/DSLzU0ZWnkl9puA==
  template:
    metadata:
      creationTimestamp: null
      name: prowlarr-postgres-user
      namespace: postgres
    type: kubernetes.io/basic-auth
