sentry:
  filestore:
    filesystem:
      persistence:
        storageClass: "freenas-iscsi-csi"
  clickhouse:
    clickhouse:
      replicas: 3
      persistentVolumeClaim:
        dataPersistentVolume:
          storageClassName: freenas-iscsi-csi
        logPersistentVolume:
          storageClassName: freenas-iscsi-csi
  kafka:
    controller:
      replicaCount: 1
    global:
      storageClass: freenas-iscsi-csi
  postgresql:
    replication:
      readReplicas: 1
    global:
      storageClass: freenas-iscsi-csi
      postgresql:
        auth:
          username: postgres
  redis:
    replica:
      replicaCount: 1
    global:
      storageClass: freenas-iscsi-csi
  rabbitmq:
    replicaCount: 1
    global:
      storageClass: freenas-iscsi-csi
  zookeeper:
    replicaCount: 1
    global:
      storageClass: freenas-iscsi-csi
  sentry:
    web:
      replicas: 0
  nginx:
    replicaCount: 0
