sentry:
  filestore:
    persistence:
      storageClass: "freenas-iscsi-csi"
  clickhouse:
    persistence:
      storageClass: freenas-iscsi-csi
  kafka:
    global:
      storageClass: freenas-iscsi-csi
  postgresql:
    global:
      storageClass: freenas-iscsi-csi
  redis:
    global:
      storageClass: freenas-iscsi-csi
  rabbitmq:
    global:
      storageClass: freenas-iscsi-csi
  zookeeper:
    global:
      storageClass: freenas-iscsi-csi
