---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    key: AgAZDn7+LIyAaoMwVMG66nRwCdAJvRf7GJuw8LfHsrwdF8pURWIXLn4fvd3H+/xg/4NEj0sxMqlt8ujlD0leXyMH2Zkd83YbXRR/VZF7BS8Bsx2zuUmP9MAY/mhX0XPpYj0bh74WZlKRTg/qGxgMizPS2BuH+0dMbAE4j30NVEZ3/OzS6ZKPJ2AANa2aebZ11aEAyUBJDdmbyGal+62HX6Nsty9PZSkhnl25eyzcYPwPf2ffXaCKKIxnunDEpi6sHIwMGL1RQAuKpmbFBBimFitYaCxOrwViq/BKClPZKB0vCwqqDRQ1l1CwbUDyia+e/OYVwIwcudbV8s9UmMcpVA9QeJaAV8ynhr/HtxaAgX2ZrBiBjeCk7QZtQDUpT7XVhpvwztPWgszUWgNF4grN2ynUsaDHbp1uCDd0Pt+5tvtDi5lzVspM/eGjOK/nQJjgF8MbB6Y4WPIHheT3tQYHGHO5YWP1z8XkePXulGWAOvHAUpl2tA3GOQxmY8mbCaqXd36qq7FCed+sSwrip8hKQCz84BoimAodXP03Mc5AGfn9SYFig2HYxIyzJUi4FMKeQGXjaH/znxXThIqEPQYzihDLxwLadRv1xrziioomq2Ut4UfBzO/7Cpl5vQ9H3E4iorNb1h1mih3jZff4sBL5t/FD4mC3kRHSGIRU8fWEkox9GnONlUPlgHKJ2ppcRO4DE/cnDm6azIxCBvoT2tzNsSb0C3FTPXpixrjegmW7mGE=
    password: AgC+qL4widrpIZrQ/bsGwAEbLjjBr6BLUhP6biZZEfeiJM7kA/ntEc/GEy7ve16eApZxU0cKKBJ3T6/nm0r8164F5PFBCVjFHn63ZIgF7loj7MvNP1jnexm1ZUdLUzTDXtrzOGdaL8CQBWCyTxKcqSAyRQVXSLspnoPhndjvgBZfkkuH8nC5YXZASR6nQJgjL2ES5SSHANQ7IjCIpH08DxS4mPuFz6dwmSSQi+R6e4XpgJoDFaX2+Tr6BbyKdPnX/HxeE1ukGvCWWqTtSh23T192vQ2HXFwS0q+QsCwABoTotxlh6tnq8SB0oawkAWhJNSQ5dra2PN6rIlc76u80dwfUCy9BRCFc5yU6emyI3sk8PzQGL68htXFfob4jiF9jHxmJ+usHR2O7PBARHtKDLAVYIPGLEQO3thc1ndLiQEPN8eBgGR1XgWjb9rISLKdOFKalm96EEqatfYYDNqxbuL+ugFoBeauTEw8aYgeH064mR2M6QFdcBrmmdU490//WQWuNmczunOE7LWbMmE2efJOSW1/zc9CjR1HAsbCeSsHnlWBhcSLooAVZaRuVErTKgxgKVwRRQMOv9Zxa1WPz5ye/w+gWkH5iOO9TFsPWN/a3R9zaezqRW8xJZPlnaXzZDJsnuw5GicZs8yIAwCN7WmEHjTaQ4B3GKkeoR3MDc237H8lVN+Q78VnYR0jOErcBmSHXo753O5YaP4lp4tQT8mRy0JuoRyL2GDuWziFytq0=
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secret
      namespace: n8n
    type: kubernetes.io/basic-auth
