apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
namespace: dashy

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
  - name: dashy-config
    files:
      - conf.yaml
