apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-operator
spec:
  defaultBackend:
    service:
      name: minio-operator
      port:
        number: 5984
  ingressClassName: tailscale
  tls:
  - hosts:
    - minio-operator
