apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: posthog-tailscale
spec:
  defaultBackend:
    service:
      name: posthog-web
      port:
        number: 8000
  ingressClassName: tailscale
  tls:
  - hosts:
    - posthog
