apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  routes:
    - kind: Rule
      match: Host(`argo.k8s.neurobug.com`)
      middlewares:
        - name: argocd-redirectscheme
          namespace: argocd
      priority: 10
      services:
        - name: argocd-server
          namespace: argocd
          port: 80
    - kind: Rule
      match: Host(`argo.k8s.neurobug.com`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          namespace: argocd
          port: 80
          scheme: h2c
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: argo-redirectscheme
  namespace: argocd
spec:
  redirectScheme:
    permanent: true
    scheme: https
