apiVersion: batch/v1
kind: Job
metadata:
  name: live-sync-init
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: live-sync-init-config
          configMap:
            name: live-sync-init-config
            items:
              - key: init.sh
                path: init.sh
      containers:
      - name: live-sync-init
        image: curlimages/curl:latest
        command:
          - sh
          - -c
          - 'bash /init/init.sh'
        imagePullPolicy: Always
        volumeMounts:
           - mountPath: /init/init.sh
             name: live-sync-init-config
             subPath: init.sh
             readonly: true
        env:
          - name: hostname
            value: "obsidian-svc-couchdb.{{ .Release.Namespace }}.svc.{{ default "cluster.local" .Values.couchdb.dns.clusterDomainSuffix }}:{{ .Values.couchdb.service.externalPort}}"
          - name: username
            valueFrom:
              secretKeyRef:
                key: adminUsername
                name: obsidian-couchdb
          - name: password
            valueFrom:
              secretKeyRef:
                key: adminPassword
                name: obsidian-couchdb
