apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: obsidian-livesync
spec:
  defaultBackend:
    service:
      name: obsidian-svc-couchdb
      port:
        number: 5984
  ingressClassName: tailscale
  tls:
  - hosts:
    - obsidian-livesync
