---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-postgres-password
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgA7U9fVgAfjzFI2wkqqRf2SyvBfHHyNKvVMyaXWrFxxu9WrBJfjBo4AYigHp9ZiczI+MBbjrZ5RVMYyMIcMGswmLusGYTDkZMPrxvLQXeTRTbGaYNRImMALRqr2A13YdRiE2FdBWfpq2GkrX0EdNizwv7ET9aZ4O7+FaoDzLLUwQpP9jf1jL40xZjq3H3mAi7jAwydE182jt6IJfeghLmoqAejLyfU6m2acwB5Zxo4pk9S6R83sYKg+C60X8Et40ngqFtocY9ZTkMJgioHkuVz5WeR2lRWjqpdai/L1W55TcweJmzkzwQbOEtoRdh73nbuSz80UOq9SeUbNq6uEgJUhqwoknLSZAOypWbgDgyD4GidtQrFN/M80uEe7mhacOk2r1ZIo1eeRDz0e1JzbkZfJkDXzGYSGR27Pno7DXpogW/NuSsNer3iIwd2PqfP8noIald09tQgN/3mI+kNm8M00q7Y2Nbyi1QX1U2Tu0OhwLRVJmPqycRWsfvCPmXUK5s6Iugbipdd67GqqdMzK6ZG6eOVgIrdgHF4AdIaueorjaGk0JOY01qAL1tMaSnN6y3AsJx74I46ttPjoi6JSj1OpDBhbFq+mav6B8tYujpl+hK08869GKCBJn6neixjy7WFEI0bDhcpQFUxQr4wbtPMgItGo+k1y0fCmqDkVcB4FdSzor/tf1MJQokLalL78qKOxEzrOe/s7IDEAqWTI/NdxEvBJhLno7hrkwWkEtrQ=
  template:
    metadata:
      creationTimestamp: null
      name: immich-postgres-password
      namespace: immich
