apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harbor-ext
  annotations:
    cert-manager.io/cluster-issuer: dio-local-issuer
spec:
  rules:
  - host: "harbor.talos-private.lan"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: harbor
            port:
              number: 80
  tls:
  - hosts:
    - harbor.talos-private.lan
    secretName: harbor-cert
