apiVersion: v1
kind: Service
metadata:
  name: harbor-2
  namespace: harbor
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: http
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: harbor
    component: nginx
    release: harbor
  type: ClusterIP
