apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kustomize-apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/wexder/home-lab.git
        revision: feature/rework-to-nix
        directories:
          - path: "office-kubernetes/kustomize/*"
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
      project: 'home-lab'
      source:
        repoURL: https://github.com/wexder/home-lab.git
        targetRevision: feature/rework-to-nix
        path: 'office-kubernetes/kustomize/{{.path.basename}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
