apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: home-lab
  source:
    repoURL: https://github.com/wexder/home-lab.git
    targetRevision: feature/rework-to-nix
    path: office-kubernetes/cilium
    helm:
      releaseName: 'cilium'
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
