apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Needs to be in the same namespace as argocd controller
namespace: argocd

resources:
# Argo install
- https://github.com/argoproj/argo-cd//manifests/cluster-install/?ref=v3.2.0
- namespace.yaml
# - ingress.yaml

# Argo bootstrap
- self.yaml
# - projects.yaml
  
patches:
  - path: argocd-cmd-params-cm.yaml
