netbox:
  superuser:
    existingSecret: netbox-secret
  postgresql:
    enabled: false
  valkey:
    primary:
      persistence:
        enabled: false
    replica:
      persistence:
        enabled: false
  externalDatabase:
    host: main-psql-pool.postgres.svc.cluster.local
    port: 5432
    user: netbox
    existingSecretName: netbox-secret
  persistence:
    enabled: true
    existingClaim: netbox-iscsi
  httpRoute:
    enabled: true
    parentRefs:
    - name: web
      namespace: gateway-system
    hostnames:
      - "netbox.k8s.local-k8s.tech"
  plugins:
    - name: netbox-docker-plugin
