apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-tailscale
spec:
  defaultBackend:
    service:
      name: sonarr
      port:
        name: tailscale
  ingressClassName: tailscale
  tls:
  - hosts:
    - sonarr
