apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.19.1/cert-manager.yaml
  - sealed-secret.yaml
  - issuer.yaml

patches:
  - path: cert-manager-cainjector.yaml
  - path: cert-manager.yaml
