---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: digitalocean-dns
  namespace: cert-manager
spec:
  encryptedData:
    access-token: AgBXRqg6Jd2fN3tMt4kfwvjzWq5BUCl6cMIgCUrVHJejAuGH975srkeaY8pc+aFgr70Lhu/SLbgxcGPDDsEo+S3ULLlZscVIkVbTYCkPOceD8d8QuTJZeuDKHPellMT7ulf+K73QDfIPI31OW/PI+CG6zdGagLXHbEOI1Mi6+yh8sMZs9I8SHjA932HnHzyDQnS+5l+3ia+houIAxahV5l4ZvHMVDp6TMiM9be5Elx3c4WJpW9XhhdSFK+Rc1fYfP797iaDupprDsLs/pnUuFeb3aMY35ZZMMj4Vno7E9NVX5q6uNHVeofQ6NQXr+DEZycTB1moSLMaQSpzmHSv3rSC+qJFg6e88eDnshD71hfk3CosNy+zyjtNn1XNKl12qbmtj6eaaZI8RDXePhhwTPBMLKkJHVJ39Zfi1i/ZI2FQlPSvfKreJoR9GRgK9d86jh8MoiRMmPhvJwOaHeDayrwxj27n22/2yS7b5Jwi0yp2Fc4WN4UJcbRdALRd2griZTyTRuAG2FIgCWHSEDfUdKbYTbYjstgcMdE/woaCrmWFNaIyXJUaPQ7JDpJ7rOi9ci+73+geertFTiz2UrBXzp9M40xLTS8dkSQBkI45kyFeHBvTCY2O/X9UBkxL/FztWMcBX4kgMjXuQjts3v2tFi/7TydNGo271pkPT2J61K+GKP6BfmFkHhsH9+QU943d6XaJGwlIrn7fjIiHJqbBXhmlYVgDgx7dhRjTefpY1f7aWYz6pzogZ7TcXJRz//ZYhsdVJjzFsz4PyMWQdP7AaRA897YskjZRRKA==
  template:
    metadata:
      creationTimestamp: null
      name: digitalocean-dns
      namespace: cert-manager
