---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: digitalocean-dns
  namespace: cert-manager
spec:
  encryptedData:
    access-token: AgC6VgxqchBhPAjzYnGbakuE+l3goQqyurfzLf/53sIiekQjQvhyzAEfUh4t65gRtD7T9ZHOwW6oJ+7qCVNRFlW2LhB8vt9xeocPsqK7S3berwY0LJJOZeOeFFAjCP18fzSpzD2TXv3yjkhUpKcgjO8K2P9yYI4esoJipXtjLpIZHIj2LZlEn9fcAP80PIsuSL8axNoZkvV2vVMMJtvBhw9TY/fuTva2uiKxTVEHZMHeoxMuWEBDrHPblo7PR4fs7qoPm/thXMt42f5w1hD+l6fuhdlpXqtqD6q75JPc4DBQ+eTNqsPG7lhxTUMcnXz9LMSMPa1TVWzMSStMWfg4c31GSzBIM0WXYXSnYJNgljyfilsVQUGks+VmJQZGPj77S1odJxu9WmEUv5MDuF7UGPWbB+4dhIQamULEcJFBqOSfdqzEoaIZzaxFTEL4TGN1sxNCJKMuZM9VFaREEw5zb3rRShWKslCxYVhYHT0qT7l92PgezcHHeWKJ8Woi9gt2sXdxFRFqgAYNiTlefr9ObYGOm4aUr5nwYNgIoeIqummoiCHW/0IjI47AKrneDg6QjscXYAce8EzVaY3zv36rA0VmurdpI32ENmN5t8KQyteJZp9eZViX3p9lbEA8Vf/+Qa5Sk5q85JN70okr8B8I6CJyHVuC9bnRPVWf6rRzPwMcgj6XDIE3NnT1vZy9LJto+PothrRt36akOmg4TUCtZm4qQps6zVt0L4r6XaUS8xZnYqrWugRpN/TYpp6mcjAZVwzHoECIdSyS+S9IPzZ0BLeXwhIKDX6Ryw==
  template:
    metadata:
      creationTimestamp: null
      name: digitalocean-dns
      namespace: cert-manager
