apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: digitalocean-dns
spec:
  encryptedData:
    access-token: AgCMsOebRfm1DcXvbXySFfPRd96Bg2lw0WLMelz1tErsujKPtGINYavybCr4Mrs64rq1K9scOFMKu2gl//adzfRz5XVj0AMMiLFTf6ooP7FO+L20XCOcV7YTRkTQraQkpnnvVHCOiudZ3KItM++OgQBDjDUg3eaDXpm8GenOqsfZOpHJh+Ixw0cqSDXRtnp+5pMGIXNOStEFjsg2QOhd14h1tbHaEWt/t7TOgjOQovVFXU9Tus1DRaFNuZ2y5j1TxknORRzg/Gqv5LRUPGrCkEtaPkndtWnz/zs/8LSzaqVsaZgDcy6Csd9ubkdGAAGkQAOYe4Iys5pqi7VDxK5lGEhm69pH17PC3San/Dk6DIdLL3AryejqGcoLXIbwgi2wEe7HClLk1VXvhy2L99KmZwwV4uJW1fyA7zCpWadyQmLXzFyBu7CPu6+1KyAqVneG0Jc5loBtA3ylT8Kcx4Bzlq07Ji7wFRqo+sJ20CgvSKut70s4ZWujeaIqHshwTyoA0zgA4UV7A6hQxwZoNNHVvhec070A+3F5bBSDwvX2FmsST3gkgd2zITOAju6Do26WmiwF/sA5V7cFPKHYLgc1QLBL0mXPhGDNu7KJptfBa2I/yYi5e1YUZ6I1obMUxIhBmCOBeD5E6x0zFkF3+m5K5fImabzlZdX16hO1jqFINzeD2PC0YwpZNyAatgeQU0fIVMlV0lyeghPWdF3Im9dbehz7YT+xrsHtkuZ7b5zrAQ31v2X4uUItlgmBSigwgIFJHo+kwbPsMZeupAL2h3/NpBLd+pyGXEikbA==
  template:
    metadata:
      name: digitalocean-dns
