apiVersion: v2
name: Obsidia live sync
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
dependencies:
- name: couchdb
  version: 4.5.0
  repository: https://apache.github.io/couchdb-helm
