couchdb:
  clusterSize: 1
  adminUsername: admin
  adminPassword: admin # not working
  adminHash: -pbkdf2-d1fed3f8ab1903afb42d778dffd0bb36cc4be64c,secret,10
  cookieAuthSecret: secret
  createAdminSecret: true
  couchdbConfig:
    couchdb:
      uuid: 97bb31e3-956b-4255-be02-850b61b45735
  autoSetup:
    enabled: true
    defaultDatabases:
      - _global_changes
  persistentVolume:
    enabled: true
    storageClass: freenas-iscsi-csi
    accessModes: ["ReadWriteOnce"]
    size: 10Gi
  # resources:
  #   requests:
  #     cpu: 400m
  #     memory: 300Mi
  #   limits:
  #     cpu: 400m
  #     memory: 500Mi
