couchdb:
  clusterSize: 1
  adminUsername: admin
  adminPassword: admin # not working
  adminHash: fn4/H97SsqUYXrtAHIgzhA==
  cookieAuthSecret: secret
  createAdminSecret: true
  couchdbConfig:
    couchdb:
      uuid: 97bb31e3-956b-4255-be02-850b61b45735
  autoSetup:
    enabled: true
    defaultDatabases:
      - _global_changes
      - _users
  persistentVolume:
    enabled: true
    storageClass: freenas-iscsi-csi
    accessModes: ["ReadWriteOnce"]
    size: 10Gi
