apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: web
  annotations:
    cert-manager.io/cluster-issuer: main-issuer
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTPS
      port: 443
      name: web-https
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              shared-web-gateway-access: "true"
    - protocol: HTTP
      port: 80
      name: web-http
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              shared-web-gateway-access: "true"
