apiVersion: garage.rajsingh.info/v1beta2
kind: GarageCluster
metadata:
  name: garage
spec:
  zone: us-east-1
  replication:
    factor: 1
  storage:
    replicas: 1
    metadata:
      size: 10Gi
      storageClassName: freenas-iscsi-csi
    data:
      size: 100Gi
      storageClassName: freenas-iscsi-csi
  gateway:
    replicas: 2
    metadata:
      storageClassName: freenas-iscsi-csi
  network:
    rpcBindPort: 3901
    service:
      type: ClusterIP
  admin:
    adminTokenSecretRef:
      name: garage-admin-token
      key: admin-token
