# Temporary secret
apiVersion: v1
data:
  admin-token: ZTEyODRhMGE5YWJhODJmM2NkZGRlNDMwNzMwMzRkN2JiZWEyNmZjOTI3Y2RhZDU1ZjhmODI5MzViNjRkNTlmOA==
kind: Secret
metadata:
  creationTimestamp: "2026-06-21T12:27:16Z"
  name: garage-admin-token
  namespace: default
  resourceVersion: "91797240"
  uid: c8ab0ef5-ba8a-44de-9490-8d0663f8fd53
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
type: Opaque
