# Temporary secret
apiVersion: v1
data:
  admin-token: ZTEyODRhMGE5YWJhODJmM2NkZGRlNDMwNzMwMzRkN2JiZWEyNmZjOTI3Y2RhZDU1ZjhmODI5MzViNjRkNTlmOA==
kind: Secret
metadata:
  name: garage-admin-token
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
type: Opaque
