apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
namespace: transmission

resources:
- deployment.yaml
- namespace.yaml
- ingress.yaml
- pvc-downloads.yaml
- pvc-config.yaml
- pv.yaml
