apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.112
    path: "/mnt/main_pool/private/metadata/transmission"
  mountOptions:
    - nfsvers=4.2
