apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-downloads-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas.neurobug.com
    path: "/mnt/main_pool/private/downloads"
  mountOptions:
    - nfsvers=4.2
