apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: transmission-downloads-pv
