---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard
  namespace: transmission
spec:
  encryptedData:
    tunnel: AgBAGpvuLUOx2XmAazFJ7LBP5GCdG/1D/x2SpZGaTM0LamF769Se3XeR26+dPCO8SGD3ezV7P79cXiI6AaAydeN5EJBxllELQDQQ+ExpSZagemxCUU12qtfd7jXFrAhlDTUd+Y/Iep6YiMuxE3TadnOxcHrAI4zgtpc7RAGCi7qr0HwAUQRTOzZH9/U6bvZrr9XhXA9QYXZi0vGN+7+QQ0i1b5gLRqZ2hpWmWffRUDv1e/O5m1wxW4j21RY9xwtgpNEL5y2h1+wRWklQns8WCJZhShWQoIP5mPAuqqTic3ExOmLEEeWb3VzS7ckwPmXIJeIQUl9xCPmuZznm8hcJs8MiLCmkwYe1xTax9V6YHMFpVOKfun6x56a5Vwr1jtG3xfIcqlc6ZwcDwpcd6Z9BZUmmL5FWyNUId+96Jc6Yy/grsJOux81aL+S5Q5Vq2P45ApQwhVQdzM4pvhSJsIAnP36kX0BeIl/Shjyxbuc8GHrjpdCqbeqOrWn+AqTofrVyRtzV1JNKCrUQ/z+oqYC3Hn6FsPGMbfaOCZS30+AcIgyG3MoUviQuyDfd4SVuuksLLZ+qyKZqX+ZX/2SnzrS1e+v74DmTG168lq/XfDoTK4NBrXkq7zBydCYThD92lrHscShCekmLqShGaSFr9TWl93QQcACa+5d1wO3JJsnhcY2FADVtqCF9dJYduth4nbKQlgAvFGhkjDpH5pUU9LDrpmP8dtEfakr52kFxTgeF/B2IEKYNepIH3AdCzGWMoowazQHEfpHpv6fq7Zg46JL2eIcx3B1YE1Lcgouyf/Zp+H6q3aE2JliBHACHmppPfx7F/Mtl7c2Sy08c55imOoqZcEbx7s1ivYeFss/KJps/QH19gxYyTpG1wPYSyge9eOdIwOsnwowAIRoIBsQX7ijOcvoCgpprj1qdsUi0rw8UevzvTj27EV2WzmLytlT+F6tdwP9DDjeq8wsKzojzdfRRA0gez7c4qYdzWrfzbWrI7QX1q+eVfxYzatVjrXcbwlTy/WFZ3hsD7N3UDpyCGS1UkPPDiMmGUEZdLyKMwGRta1v6iGZUKwMwYl7Pw+i+B2WBDWf+7wkI62qxenHHqz7ZyIBFrSJvxBck6gEDjGEJuSjif2ICNr+JBehz4EtqO0WJOjXn71NcMNGCBvwCUc5To4cDYLdnbLK9S1GITpxK74KdrFzHJoGWZrEHALFfHKtbmILUYwAzMx97DI7s3MN5hQi0aGsVvJV0t8EBfnqzdk61CRUfmnjt34MzhbMtzZSSZb1R3cH2M6D9FVZSqgTYgkQRgEn9lhU2G8eCYu4zca75I4HMpuljXSUrkb5U9EOvmhviyt7B5SKRjpIyLho3Tyii8YCSgwOD5yJQ8zlmTHsmFZVQ0kCXp5Kupoaje2pz2RCdrY/UQ4s5uIyV8puaBBb8Uj7L1Tw8MN6/5IFXdBNWCKJNhIBQ7pnopBd3FPvG3gPMDLTMFD1fcgM5xZm0Fi9OkH/k334ntSljEOu8llJXT+aywIy43ie60JNZlCL6VkCGJaaQV0i6kFfW49yxTwcNihtk722r
  template:
    metadata:
      creationTimestamp: null
      name: wireguard
      namespace: transmission
