---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard
  namespace: transmission
spec:
  encryptedData:
    tunnel.conf: AgCoTN1ox8fthgWvS7f/2a4Qo3YX0U6er7O/lcTVcdwzPyDb3h7occPOIVQSBdLrVbFm4rKa/40jkkDkBh5vdQUw914o5gikX9AYtZTKwWhqSQSrYgzVY9p6M4N+7GJm7GO3ZmHQXK1tNaGHlasNkdWtS9WZ72mzxDSyzisvE2Dfi89UzeqmNilFkd5scNeIARIHLn13UUxIYcqzuBFLSj90oswwlzL4nOcZNZYJlshiTC8Hx18zz5YL7oRBWBV6g93vVUfHwbqsdXUYzO1j9ezRsuw4eo072O32O1B+ScNd6PmnWJlDlBr6PgYbvRdAKo9ocC1gy3K5HLCWmZZByWVZFi9fTTB5918jUUZ54on5Aq35J+gMhUUYBtcNdmA3izcyaMS9kNJKgR6UZQhLt5ktF8HBRUaBBA4sUVSJHduz3+hYv4RZb6Uqou94oDdLbLgKhtt1/x6G44HnyvLnp/6ubX2pSZd7oXU+OoJL7VP5Dh+YZdDJbdnUIGZWkC+ApkcuFjGwC5DISqWxzaQfmnWfDmnW/v2VU2kgzqGTNmMPmZX+2NXIHm/soAsiBg5Qvcc3nOMK9OGgzCoS1xFW/Io/tQGJ4Jgdyp8aRwQWj4IzfiIUj0tJVP7aT0k1yDd//g0ZyWMh2BiBSn0MtgtwsEEvx1tmKS0nA8v+WMMADBW6feHGEuYqTTQkFyc/O6p8Q60xD+/BMDOKz/Ur3idQkDKFk1Ne/sYS2A4XjF9Gvu1VxDkC21WBZIgcKroa+8fXZ/RqN1lpDPDDAKX1CYeQhli9ViNLyKPbRetUAWY77rQzFZBYve8yCHGCtHcdo5JTnSx5C1HoxX3tIHdMl49JN6Ak8BdDY7SEfDAfFD+9ohfGNAjJIDGKOBuilw/ywGdS4QnywuejaqsEgfFtyh5ayfxJl4Yaftp2rmelGwMqVYgQNSeDyyZS9LayoT5TNal7GqEGCMZONw4YOAmzIwohBoHWi2zNm23EUR+Ua0HK8rbwweoVzJozmpaBwKZ/LA4wwBECefgonyhoz3bR2EAFMqVAUFNgRspplZTVo0L98BnqNI9xKz/PS+VwhHHfhIZNPuLz1+9GCdW0JiS57HMWl7h4gAcXQ5obSumHHn+0maOfiYroQoNbihINlu9zdIRBtNbfaXlMn//3k8YjHcH/JC5flpM8WlGsi0aCR8nEZnzDt97s9pXczMoJaYNYnUwH8CeMDnPnq74IwXTzrleyWuipawe7LjXugBMkkrgKlurw4Gk5/PrTito3gjKO87FLC7OcAY3nIAlwJsXhMCiKiUHD0+dmjK0RWReHf1EvIX/ieYf38aRs2djQv15y9eCwt2wip02uBd83eHqj431fhn8nmDydao404JRNJe1zFjSWrrJcwE8EIwaHTE2eoBJYszUhsDoGXKNeA218zNBFXORH5zfjPwRAGDORZzXB2IQLnAMSKIqR0LUZXxKeInCsCBsCja5/2FLU3D5SEwn2bd4hgP88
  template:
    metadata:
      creationTimestamp: null
      name: wireguard
      namespace: transmission
