---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wireguard
  namespace: transmission
spec:
  encryptedData:
    tunnel: AgCVYuiLnzQwPvqq1ZEkax2Y8EuySUajM6lSHJTVVC0KzzdA3Mne8JMOhirj/7Jbr8lSWTNrDnNldh5pKtfgLEdsMB32washbK7ggHqypKJRNHIdSu6yNDbCMr4Htma3GIu77/goSHQuqYBz/BTqjQz2rUrykkZWVa5JtdkMlssPnia5OAssiEgosYU0Z4ZL6xga9fvEtXWgCQHnEl70fEHE6Mj7CL+CtZyK3syyufczYs0BZrwUZq847fTTG/zAVuXuHRbwLtiQ/J5JxQtRr7WrwIYdogrXQTf6DC0bVJ5K74nWyOd3k1yCsEykCkMrcYGxYu/fuQUKSV25/IJ0dUYW62inCiNQraHHb6EKFS3ffE9zaaUdOPo1WU3SaC1gAKANE9uUcC2cJbAyA3rgqszs3ZlwaKlEAFqfauF6DsWInlBhdjLuxEbXm+08cpkBs3p2pW2mDT2yIY5CwiZ8Qa42w3qoEuTa5yScmX8K3jah64iR5iRzhhpHXDD6YMdQWYcuNoE/SlGRuZrU8++rHmTzCgIvP5xM00AsIYsan/MyxLkcmNK9IUqYoSDxn6uzES8fkLl4Nr2uti+bZAdjhgW365mNxsXgIqQUbTXUptpGMsEAL0WG4K/GfJmgGUrTvvIvbnjTb+U060CtdL6diuntfJ8YsU1AC7LlwUAy/F3Wjdfv7/B5BHQzy4QLmeeBgMuSlO5Vc8jFpgcyLj1ExZTI9Qox3LntukwU3ODA4ishEayrjdmkL+B4EMTA4jwTmtFo2Giv475ByXMfcEjcFcGANtyqIR48w45ZjHWiRqXG41dSEvNXwRpJIXWpsE/AJxBXkAGUrsZoDzc5pdBo8+aMRHDK1qsUW9XBEiFyLxtCTjy6GnlKVoKKAaRzMOXZZ7zLcI6jmLyry+o3j2lMPP2/rttzF3Bh0VaFwGF8rEBry6tNG55dP9OyUpL71ZuJmDoSR2A0pARzmwKQWa1uRZujiH9vNSPgAYeUVpvZuQ7vrR7SpKyHGEX0//dVlX1b46vjjCIZPJ+EbP7ZCRP8LGZmVYHezR9iQ9ugGtYTqKX/XCfUKfkfjAA//E+MHfiICgvP7SnZdJfKXCASV5ilpEYod67F7ZYtLmPA8f8oK/7hwZtaor9i7q8HCGq4qSDUVz9jPyJ0QqxE3hJVp8CmwdfYAe/dW1xjTG0HjChSVq2LAiLl4OEC+xv5MZrvMX1AUmWbjrfP
  template:
    metadata:
      creationTimestamp: null
      name: wireguard
      namespace: transmission
