apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  ports:
    - port: 9091
      name: default
      targetPort: 9091
      protocol: TCP
    - port: 80
      name: tailscale
      targetPort: 9091
      protocol: TCP
  selector:
    app: transmission
