posthog:
  ingress:
    enabled: false
  clickhouse:
    persistence:
      storageClass: freenas-iscsi-csi
  kafka:
    global:
      storageClass: freenas-iscsi-csi
  postgresql:
    global:
      storageClass: freenas-iscsi-csi
  redis:
    global:
      storageClass: freenas-iscsi-csi
  zookeeper:
    global:
      storageClass: freenas-iscsi-csi
