kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: netbox-iscsi
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
