apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: photoprism-tailscale
spec:
  defaultBackend:
    service:
      name: photoprism
      port:
        name: tailscale
  ingressClassName: tailscale
  tls:
  - hosts:
    - photoprism
