apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: syncthing
  name: syncthing
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      serviceAccountName: "tailscale-sidecar"
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: syncthing-config
          persistentVolumeClaim:
            claimName: syncthing-iscsi
        - name: nfs-syncthing-data
          nfs:
            server: 192.168.1.112
            path: /mnt/main_pool/private/syncthing/
            readOnly: false
      containers:
        - image:  linuxserver/syncthing
          imagePullPolicy: Always
          name: syncthing
          ports:
            - containerPort: 8384
            - containerPort: 22000
          volumeMounts:
            - mountPath: /config
              name: syncthing-config
            - mountPath: /data
              name: nfs-syncthing-data
