apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: syncthing
  name: syncthing
spec:
  serviceAccountName: "tailscale-sidecar"
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: syncthing-config
          persistentVolumeClaim:
            claimName: syncthing-iscsi
        # - name: nfs-syncthing-data
        #   nfs:
        #     server: 192.168.1.112
        #     path: /mnt/main_pool/private/syncthing/
        #     readOnly: false
      containers:
        - image:  linuxserver/syncthing
          imagePullPolicy: Always
          name: syncthing
          ports:
            - containerPort: 8384
            - containerPort: 22000
          volumeMounts:
            - mountPath: /config
              name: syncthing-config
        - name: ts-sidecar
          imagePullPolicy: Always
          image: "ghcr.io/tailscale/tailscale:latest"
          env:
            # Store the state in a k8s secret
          - name: TS_KUBE_SECRET
            value: "sidecar-state"
          - name: TS_USERSPACE
            value: "false"
          - name: TS_AUTHKEY
            valueFrom:
              secretKeyRef:
                name: tailscale-auth
                namespace: tailscale
                key: client_secret
                optional: true
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
