apiVersion: v1
kind: Service
metadata:
  name: syncthing
  labels:
    app: syncthing
spec:
  ports:
    - port: 80
      targetPort: 8384
      name: tailscale
      protocol: TCP
    - port: 22000
      targetPort: 22000
      name: tailscale-sync
      protocol: UDP
  selector:
    app: syncthing
