apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncthing-tailscale
spec:
  defaultBackend:
    service:
      name: syncthing
      port:
        name: tailscale
  ingressClassName: tailscale-disabled
  tls:
  - hosts:
    - syncthing
