apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncthing-tailscale-sync
spec:
  defaultBackend:
    service:
      name: syncthing
      port:
        number: 22000
  ingressClassName: tailscale-disabled
  tls:
  - hosts:
    - syncthing-sync
