tenant:
  secrets:
    name: myminio-env-configuration
    accessKey: minio
    secretKey: minio123
  existingSecret:
    name: myminio-env-configuration
  tenant:
    name: apps-minio
    pools:
      - servers: 1
        volumesPerServer: 1
        name: apps-minio-pool
        size: 20Gi
        storageClassName: freenas-iscsi-csi
    buckets:
      - name: apps
        objectLock: false        # optional
        region: us-east-1        # optional
