---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backstage-postgres-user
  namespace: postgres
spec:
  encryptedData:
    password: AgCPSwtk2lURa63Ugtta2/ctFUyVOcRfCToBXDs2RXMucvgTCHDDlhehNwbBjls8GKcc6PpTzRUzSFWD9eDDF+QT7ZguCcs4Kld9eE0GT/tEeO6KKS/AT1YRYSvf7ZqpMlnKRTJdyulqr9Cr+4bWhoz1Shddz0g6d4XcVQqqdK/TM6TOxyJQKqI6K1+Jl0xxFOpxVxhtOyxOGD5q5gbAK5X1AYCRUB5KH5Lad2xasm1kgekJOzQhqZcguSyrubyntWtTMvTi58CBfytQqP5HqwhgsRjUZDdsY9jFTf9ZmUjVdhiD1nolM0MbD0vuxdyf5ue85omJaLNazN21H4yODBx4dxRToh3uWVN/K8cbDn4VaLzRmkPLwi4pD0nA5DlIF8pBR+VdC0aXpb2qMuzrXeFeqaA0Nf9GMxqWYsZTvqg9EaUbftqsSg7uDZ7vIz+IAJrqHpVK9/kolQZa/9dbdu9DqgdeeBzAB0TAMhbbkih2z/K/VJhPpcne4/sO6eymNdGtPRMBlvApobjMynRYGV0+6RWIYpEoZaiJOWyIVbK6GtaW4NtE+USMczOSMpci4U/LouEhoajkWVqew+dou+RjfgLXDT55YTVsxj+7HkmJMxdhapmlz72qoQ0+dtVBb6Ua47zdR5xdiPs3A+pcBufqYUawI9GFy1E1eG20lXzh1TVjporOww2XXwHxuYzZVjYALpmIw/LCMs/yWX5e11IdRVjfYA==
    username: AgBNdDYdg0gU98YaucRp65M6vw8wQCZPr5vuOzWVMaB7rQINwrB/3qIeI1nUHDku0VO+fwzTRMutuImR2HkH4JWLFitdzpX1SDHgEgiS7fLxEgoZ4X7fPB7Cg4lYzKTa00m31Z7RNO0umQAen+jtbwLnriklEChQ3EBMnl8OSwrE4IPNCvfC3jZR4nKaiZJuSYKUlyGIMbyPV7S2uZ1Liss3ID4VuNbgubV6OiUcF/AMqJF6ImpkPFCHZOzktq499Xi9vnjS6MpeOw9zanh17ovC1l5ZEBTlgZBWCCoBL/FxJQj+IFVPd5bQ6szyGslbIvBCch1jdhgmNpAC7ilUJt8jq2WPUsvdwi4G5ejyE4zDROMM0pNNb6trIAUYNXvfHw16WDJ9nGwEBUWWk0nQV4fRa4nkqnJEB6VouBqRZhaTUR3CmAxwnaGUn+j8V/pDBtB+XP7U2pmLKMRLVG+eAGJYMtRnwOWLmPKE7C6idp/2wC1BsZX16SJoUMs5qTAc+U3gh82Scgs2yfVfI0Y2bW1gG1uocsBysYzilANtVxTNZcK/j5jSsNHj2WIXqXqYFwuJX0dPD//qMpIo99ebJ9wNt6o+6z96asAqJYuxPc4NRcbfzHXcpGD9NxglKYmzgy2ARiXIhVelU8TqYn866DSuEiFjQaKEMPA4kW3UV/27XupiAlH+RSpQ6bNtrHD+rY/yLXgt62wdh9o=
  template:
    metadata:
      creationTimestamp: null
      name: backstage-postgres-user
      namespace: postgres
    type: kubernetes.io/basic-auth
