---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-postgres-user
  namespace: postgres
spec:
  encryptedData:
    password: AgBp9Z5miRgkqWIfSGHsXhpRZkGv7ktAs5d0HYF+excfr8X9algloLUyk3RyadlFel2pC/PZsxeGO/Y01xsHc16aYXQmEFK8i4zNJTOYpQSVor/0M6MJP97K4C5zIeq5i15QlARxuylbflEao8w5Lfo436xJkG5U5Tcx6eGnwzk1lmw+pYF7i6AYJqP9QuySWkjzTbEeZHQGZZ7HSvD6gX1r5ZmDAMtNZukDB131EPP/N7ECNTCIHRAhdj/l1rsbNA4Y7mtGJqhsMLMa5JRlobRNZcKQ2GkICL23I1RgvaW3OO5pjOIA8llbtTp+X0i5scw7VqybwNGccP71933dbJV8O2dEzNZHgvH0EJS0aNMOyxJTAzoWtVV/kn9YTd24UB6+lRo85AOOpLr7kI3qN6aCRAQAjcCKAmKL7L1zYFk/CKz5QbckEHn6cprb3fwJxlGPwngjHzqtTT1TLfBQgt3droVvGEkH/klXwFv0LsYmtUq+3No/K/t1W1qHh+BhXEK0dG85nQxhxYdUB8onVP7ehIaeSr92MTsgnb0To6VnMAOahoT9DlEi5BqvEOm4zsN583HmMIgVyeWWbgg3KW7QCVbbIqrzTYM5otdwddHXsqkY8WmgWIC5yf4T5bZjLOD55ZTM01atqD6/C/LLF+PG66B8ep4c4e1PiMR4o09oVV7YO7nl5jwbKLUThBFfjnVCk7J4BOJ3/qm5xxTaoA8s9rTQIQ==
    username: AgBySdy0nLZDPPl8fDFmI8Jekv/nzb4CdTsfZQvzI0IcPLOObzV6kflsXd1GCOoR6toBkaGuLf7oCrxfHRJTvrp1zXC/Fi4hLdhvbB5z1OfFzQsrQh19MXIGtjInJe0wQ0mwc7zfDEYL4ob0/PKSTuDevbXYJDYmJI2L/5BmDQTRk8nlQVyL+Qq2Td0l4ZwecM55ManfyNoml1zdwCRfnp4taaIgLc3rIxCm4SQtEKe8rO3mq2yKAQwcinFmGgeWlUuXeeV2JL9cNq/WQ0fdtkvsdfTHfbX/V1jzLtQcyMdXQRgWYDMFE/DF04T2tg1IcrmgfAm5xgV3lRnB+JWkwq6Smk9l0nALs0IU0cCLoUUHS8zGdXqmV0EXd8Ru2SNGjDGKsk4pRYutKwtrP8g1EMylRM3esL3oR4FhCxxFQklAW95gVnYub7I6DmLG3oI8070mokrJlzFxwoco8PofxM7+RRrlsRPRlG+KQgx9Z0dJVERTlqdoWFftHvjfanbHJLJFwFevWki6T3DDNMoa2lxXVl1qhM0QHEFAPF6HXUu0YjVOndtfbYFqZcnVLeUWzKlJn3KUtwuNKfov29kdTo3hMRhX/hCcv8rRRpvHavbe6BAuFP9E6w5Jyp2sbLHTOKmQVmPGIKnpVzyLFXhkEmsnosKswQ65Cu0qZaV6F4D3k43p+zlAEGgGHge6894xqnP53uzmKwQ=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-postgres-user
      namespace: postgres
    type: kubernetes.io/basic-auth
