---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgres-user
  namespace: postgres
spec:
  encryptedData:
    password: AgBXP7XDTECHzmgoZiGRgBBRRVxI6AREzG6iTrBhUCWycrmwT3T2ggFkIlbSsBRWsXxrXNUylXS8u2ydm42FBN7vZ4oRrIIRIT0or0fdnRdzlpGnE4R+tVVBrGh6lilIMCWHscs9hdb3MzEaItzTVEJbvs2N11h/MzE8/x9SxYBsausfwPo1DHtsHHmn8x8D2eqM5L0m28JVIHm9uUggwa2ZvTSbQkIEVeNKNYzxYCrYNhvHum0pbEb9JSQr4vnsyyafnxUfbrgmUCkB8f/0QSQEcCLf+tlpldV80HZW84ciTmLMDhS5CixGgl3h9aWBWCxOkcJY8i5hZP47l9SXEUd51rQ4+8+Gk0JcZK2Q4alSHFWk+udocCkEQ95YUT2UsVKLpIbL0d4M6L5eKFvH/OptUtReEBG2MjSIy6G0ZQLE6juw4y0G/i6VuH5Tz4jnM8H2d526rAUtUGcO4Qf7x6Q0tB1Xz8iw09vu24BPfAvOCdnyj2K3OqwTm/3CXws9rdMJsvVZ3TdD2sis/Yd13Qd/3aJw6JGSj72uvuni/5tKJPTqP0ntbO9Z+h8RrOhULRGHGUcppXunRgZKX6JXcCQHnWRQe3upxXdRb9A7bu757/JZ+4Z7bJV6LC8dC2ZCAuVn2aKEgY72eZHp78Rwy48UPaNsuFkoyHpxWAQVT816xjFCvSBEFbBZLxcQ5n1y2OaNkLfvmob9LPIaKVl951HQ
    username: AgCIz+0yEv57B+DxCw4i8xoanlWVo31inRrCInpMyUx96cu8dbZfnBfyJg4ZCHKWxqzKm05wJHQ2h6MpxG1bDPOn8pwqt1PTHYXbxDx1XvPgrZrJ6gq0Jtwg6T4+mTLCyj0kWKi9NDTUHonI+SM2D4O6CBtLRhH/Bpl0FnAK25a3YYwOcGN7hOwM1soxiUaNxxXJjeGrfupg14d0QgOrnkLwaWttGmoWjNyt3ZNSonbCpN+JHzmDcOJ6sPP9zTexQdvR1cep/+vdfsj2TplKT0TRAyPckrnWn4l2CH/VBMZmr4LwyN6HsbL2O/ZfhozNYN+4YYrhz4KAX4We+8F1GCQHtU2E1VOK5LF+FzSu9Zhqlfkm7KYPM1XT7tel9SSpdtrTA4xzgnta1RNFr73v1qMX3Asjt1Sy2Ng1EoBfQzFjx/ujtr/TgV/ms+eKbAozx//aRMEuMR84vc/QWTyzdFsjlniCq3i4mgSIaNvHEDcjwgjtpV52pi5zmtvyr6ouDZVAUwUYTLoobMA3y+jP/Ql7cawS0Byky+pM971k8EzG2K2XENiEw4GqjoLw/l+Eud1o4T3Dbetjnd5IDuyzTrk3dsre0VZqrUQFnBBGv5HzL4m5GHINo5lwp7QlvQkYhJEDbNReTasQckxaSMp++whbxt/vsELiyr0521FzkjG7/bRsBvEgCs6G7KPfj0VkMKLWq2sqZhy1Wg==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgres-user
      namespace: postgres
    type: kubernetes.io/basic-auth
