apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - immich.yaml
  - immich-secret.yaml

  - sonarr.yaml
  - sonarr-secret.yaml

  - radarr.yaml
  - radarr-secret.yaml

  - prowlarr.yaml
  - prowlarr-secret.yaml

  - n8n.yaml
  - n8n-secret.yaml

  - odoo.yaml
  - odoo-secret.yaml
