---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-postgres-user
  namespace: postgres
spec:
  encryptedData:
    password: AgCph2Uqq97FFOpq5EwZioWQcSXh5adq5BfE5ijoRrCGsEAMhAl5K5XQlnNjGZ+5xCP3VJ/UkQ2ihnSRt/aM5tMQOVH29/nWlBFiLkK7K6SCtlN6mhwmzwoPpS4kP254PGUU8ujW+G1I9ygDHbxlsFNRBVy2uddWSgeFe/YMV0AYKPBCouzD7lY6P9DtWV1tMgce+lXNjPFSFvLmE0nwAW8WW8CjnQXKJPRN1F0MXNDaKAtTnEyXMvUdUNJNiqFh67C9XN13taHO7Hh/kiHsyGE5KJQDYrjWorr6/zgHPI4+GizzgcU3cTHZaHQzXam5TkWUdVSkqPddh/3GKfQkTeG2CBOUWZz0SWejJDMn3RXCnP0mDtY/xCyqdMIQm/jmTNRtkrUosLjEKUjMO0tNLDUA4LCvckGJQghDUcSLbp2Af/d5BGwejKg2b2kBnvoTE4awjJEYTozfup1YPMnRF11vUvOQrnlOreP9GS0eLOvpyhP/TpV0n0rNjWoli9F/IqiUW26AF14RJ4qhgcGnPUUIZi0z6XlBCsnvDhu5Te7cs6BssFBqi/pOjh6Woe7zU/5I7Csj1b36FznT+D4IUrSri3GbaVx1mnZI/JxmQmfSfyEdh83K3d1Bsflmfbq9rorVYnlAH6+R0WjzO3d9EDdyy4rjervOND4w01ghNHW8XLtKm4VbnU8sgr0YsCm0NPOhIz+TT7MSIsxT8KshU+m0DqMc+oxq4UvYwKuShHI=
    username: AgCAqKeIR9yv7TKSopITtKIFPy6nCpyupnkBysytSGOjCwV/rEPumL0+2j8gUg2P1huDHSqkNE8vWyBttJKe+WpDdwBHuYvG3boYGjd0Kq7CdKR8mHT5PcigDCtXGcdHXJXIXZ/OHpnMhd6G+MOx13aLBPY+MdkVIydtk/Bnw47XeqnpdzvlTad9nLmSZMokF21SFvijtgPcNqokR0oqhlPE0wXpylgmkaLAd6V699fvxbvG79BrUVeYwfWF0yGGP7TsyO4ahY+h4CG0NYMdVHtSEvvhBihj3KJFrpwwjaVu1WtMKzH98PcBGCOD1/KB272epY3Pf8dMds3LMBh/V1NEHbteTLJARMV4GlepK6GhQOyamHb6dqSf89B9vp45fnSKekkgy4keh+WgFQjHMf0St20LmPsZQaL2JdP1ZLJglz2G+IpAomWb5Wby1mU1K6GlZ5x+cZSmtlZRVNkpEthKW/S2ldcH+goolEKOr0m7KhrCyRiMkwRYYSNKLdGO+gL7X9Q019pju6z7iAdC+gvmOWiejoFVW18EZZSmc2/FdnI59fZ6TXi7Vwj4uKcav+MhU77KApdeKXB4fIqYBsH9xP/dVFhLMCyetFXnnPk+9UHTFtX7mAcAeDOJAj05N9U1xrp/zkN5GUqV9XGmeVuEHZvt0yKi6x8MAbgRqhYBUkSxf+IrwFvhJqki61XYhWrRmBA=
  template:
    metadata:
      creationTimestamp: null
      name: n8n-postgres-user
      namespace: postgres
    type: kubernetes.io/basic-auth
