---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: netbox-postgres-user
  namespace: postgres
spec:
  encryptedData:
    password: AgCDQpxw/tR6MLLqVrl5ZDMCFMSpRVBi2okZ2MlNFnlqWPj/EVQwF9dgh95JoUbcoVb6NcVGRAckwU9XjfZZQLSQIeFQ+SSromcsqn4jacVVFohDGbLicxz4BqMrRbFeKPLoIEyQ5e7S6Se979XY1zOf5D+LZSnWiG4ZsVLYoB2fVdigapfPlWU8LakYRfd8JOfiJLQrqlYDGLamviaC/yEQp1BSwS1iN2riLiei1+8/LhzaE2cQMKGJwuOt4paLNvSuj25AEyCC3Galw1V95UFMCtpT6/g3cP1UCIRxq/1HS5vkTbZU0UfXFuaSpEjU+jHDvmuasq6VQpv27aQ/whz2m5KSTIRSF6ZcFvTIVGr/3UEI3aURoqSUtBC2nS5QUpCUZFFzYi0+ql5lY6zJ26u+6PEWMbP9dvkyD4764ShC1ikwaSUiNIKCPbyA15c1MqQVffkUvDCwLPkydnz4dKmcocBvhwXG8uhuJCDkS1IXoe9GtdgYRsRNasX+v54s1YxOm0rS/80/+ur0BiJNNfeJQ7hNYW4QzZi7rIrCH5G/tJjSaXeDkGwNx5wEi7Yo6m3ze9c08tKtBijS9Hou+IiCi05FKo1nckUnt7HqkUMgqhIGc3V4kwDbAN474Lex2YbPDZ+cozi+7BFmh4HupYWTvQdM8i3XudKFzfYbbFGXiyvfTUKH/FDNhOiYOjEKM+MQtmZnLzlAboKXCFW7vfh3Oea1NKFylA9KZLcyJao=
    username: AgA5FzUnci6xJ6/otoiaLNwwB12OqMIP6fYxPNphpEINQ4xIC0NjrwzuFL4eDeDOjBv050qHYTt3G8/s0pl3jgs13T9BHHfOVwBXSuHJbtIyFYvxL+n7C+6VkJh8y6tyzq5kJX5BdV63kkZwor3S/NF3tTeKK+hMNTYzOTq0Lq4zzG24dYRBR/Bb0XXpwMCu+FwmdbSL2YCcK4a38yA1hGWFrrPRCDpg1dfnYOG6V9I7K/EktPLbKo3w4wgVJGSIfD+oeIL2VSchTOEe2zKI17fBEyhblgOxQUaaLSkfh82la6E3oTgyQzbnbUAifkgQlUalQOZSn38QWBtZ/AbLDcPHgvFSrFeW5Z9FPoG7jUQJ6nPnL2qrSdaSMUtEE5SmHCStFEV3CdXz/3T84qQgmKYf+cXEImCGc5bUjkOfxh4BVPotG75yFJ7zbRC0LxZcPxKxF8Vc5EcwrVWamMxVib84bmjfoOuB49WiZt8RSBVF3tJZ1SuxgzudKbSe6P/T39o47dXnqDfzJ2Ew3f85SiKOyRym0Mqcghiyx98GyYvYNU5VjUmgt1A9JBOqP/kWnIhulTCGZaYOmhgTT/R7mk7oYCJ4ne2s8nSzZxAIxtCDlKmhxLVEJRgM4IeQ6KhYjlgIXbogm3oqOLVLAW4pSlWgAXvukde85K9EGtNt+Hk+NZDqO3UBkwfi9qtUNJJJdDKXDkexEas=
  template:
    metadata:
      creationTimestamp: null
      name: netbox-postgres-user
      namespace: postgres
    type: kubernetes.io/basic-auth
