---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: odoo-postgres-user
  namespace: postgres
spec:
  encryptedData:
    password: AgBIAAOu1q08j8BYn5QPgDi2TSmn43DH5OEsvdkSDSQu0Hh7pE0k7827kskM6uo7WeZ0+1LKERjj3+yBNabJkmutOnbYgH0la6LoZugX19prWYnYqi6+BCKQqPxeXHHbX/K9061r8Tdy1nSaarKqjJT0bZ63SrhK5bZe2dzuT73n04+FIKiiBdJewi5q6VEhrKlS8Q4XPdLlvjsfXV1sDyQ80blG2kyFpMONFzD3fbav/snIhRcSBPccjaWqLjR+OOZj8/PiPxlEpNFxbSpY5YRA+pa4Tbtzho5VMUPZAD0DsRaUnkbcoCnHLCShJ6umxGZ4c3fhgrxD0StE9P2vzbGr+RImmt8n7WPj/uT9XuHYKZO9OotzYCLgrsU06woqjJAd2ijKYpQhp6endd/B9yyw2DUGTHPUyZ+2RCs9rzm/YWpEYdXfrm/73U5es6IbzDv2O5W009WsBljEDeFMaDlAZKBl8Mre/okxOwH5p0NWTpInVR7qNZcCB1PUNcsPX9hzX4m/GaLwLNiASTwpa/GK2gqpK3XnhVDTMaJexRTZw0llTKeiR3zRB8c7bDDP3fr7TP21aC/blSQjxWCvTJzNcDorh6HAgkGofjj7d+xnX+O2uuQ/OpcqpDhpEo2VO6IuTBucL+knFyH+90DGzSsDt8xS3nbp0uGXfduud81Pw7wNko53y7oXeitXLhrRR2S4MUJoRG4BPcBU8ZIbr4+5K9KstNIxCkQMW82EVWs=
    username: AgBGpexgD5+KLMINsk94F/CxzA763XEcL5vYxD6GSH8pmvpsGBWR9Oak4fGi80GetSRH5pFwSd8Q2OS3aYHutom0tfJ+OaZL427g8JtIYsxg5sOTq41yqvTjBo4nm2AgkT/ZOtTyaHN8Q52aL3UlUBD5tCO/yWSprD2fnD+AAYGOsF0lvneWJJdHe2jUGLZmhPy+r2kUkbjrxapaPWk5TEctWzFNm7Wb/nbNgpeSMvso22SawV/MPqGClb0kwnOh52Ei9AWjQlZ+WiDb1vOwNu5gMYx6EtEyWFGPzP5yFzMrloR1Qg0yL+HKE9vlL+klniq2TrQn/7K3WOgRdJmVD4G8qmMfgjyi9tcoUv/Mcu595UFAt7nXf6e1y/ouvnYHkZZcCSts/i8hcuU5PxP1364c1SMjoQZq75mmBS1bvViaSgVVTo491zaeVzV6wsLar78Wvb5CM/TtTJozcsoqK60r3SToawCKE4u3svVlFNWnFeSnh0+ZPVN8QHTuUYDBHbfXitXkuEaAa/oEf6TOkysEc//t5RDphGBZq6GK74lpZljayM9yxf4hmWSIBRK+tz2+Nmrc3/wuewadeupv++TYF60DtOGt+8WDkVxc/3kaj4GvjJGbPrsVeII05IUL51KuRnqM35zpYXFDxbJQDX5N4I96LxpI3nycn+HugKZ4x8yYT1N8o1PxaE9q6qGMOczyA2dM
  template:
    metadata:
      creationTimestamp: null
      name: odoo-postgres-user
      namespace: postgres
    type: kubernetes.io/basic-auth
