---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prowlarr-postgres-user
  namespace: postgres
spec:
  encryptedData:
    password: AgA2OynTj7ZOFX0Sen8kH746qNVPK5n1i62FCft7VGwZiSDCnkTvTPs5fJjJMr/047O/c2yyQTEVTJTbU7mrQgqcbpZzh5G1IwTtm2e8CM6Bv6EOl0oWz0rkimt2pxmzp3SW661f7EiXQdt163ZYQUY/XeG4NER91sCB+mjtuH/Rb0+pssdas/t5cJ/J7+CKeXycLYL3He+SPm5GaU89+L/jY/NujN58CYERWQ05dyD5SP52DFGyCdnJSfvh2dnowbx17NsmJ6fDivl8XaHVFtOdLA9l6UE8HYUFoPq0Dj0S5EBg4Rghyjglq9VtjQ/2EtC3wTI/ZWJGci4tmkacEZ/QweeRZAoTvwLOwN6qVMGk9zpJFl842m5X4Rk1QM5ROI7EqRRJKUR0Ju8AMXkPi+3ASbK9QRkmo+iy9UBRCS8gD0+asJJcUyeA/Bu+vzX9qppkzbxO5zSDXadZFCf/SLN8D9XOtCDOCyeFVE5QJGBxokOdDoIBbKyvP4V/Zl0Zp8KueOdDS0xUcvip7uUl03NhoJe1PKJbxFg6hSQJeMMdULq/GOiMx71cle5xSvDBRgJqj5x9D1g1F2R+Z3SgmFUYCUTlD6UVYiB5RdEqt91Ph1MSG8WqC7O7du0NSsGllIbtshhN0Tt/x52nH22uTgH1ZPPCNTrMDYM/iJhU9KBW2yfmEnzm5duSiGrr7B9YvvEZik53/Tg/mBXMbxxcDA4KPQcxOYRrQIH7tBOTz/c=
    username: AgAAmIVwDgvAySKUoLYBsNkncDnCYuuZBLSEhsDd3PO+HWvqBHOm1xTr1OUnljAMRuNx2lyOu4r0jsT5qNLO+4j3I6ysUL9LwCLbN4f1Y4J4UgBvKSuG2iletkSoHBXg6LUibbjAFWr+Yod76S2/QQTr2xFE1bpDj7TKtXKqdqHBkbWX41VH/9tcVSs7G5cCzqwAThBjYIEh/D1BmdDVBFKsw6XLkh2AqIHR/A0DgAO6b0TLc2aDnHd+sL73gHKfztnBrS4gRq3eccIlscPjA33cwSCDzWXiX8M2O78WyUkc+mh231RUelGEDsVwlgkYsVOD6N6BGoof6mVL7qY9Uv3flUv2f+3OfVDISeNj0oLQCqaU91RFgGohiA0XKN3RrP+x2vRlEsOC7k8pn84+JXE1JPNYo3dyVrqlYq8baUfxPYEBEItrBgNikoQ4P0r9qlJRCobEx0E5MdZKFOjZfxmoiftlvgdIz4v+al67CG54YoKULbLPSa14VZv9mtDAUEMeUfURBByg1OoZ5Nm3tuF4ks7L7hgTHHpgqgYZUntRu2V+g2XkBaZ1M/Daner9slMwGdYAKo0wVuNycVAoHsbGb6dbx+qckvuz2WfTVrV/M/fk6m4VRcImf7JSKcw9PwaInxT2l42Rseks2Ao8B1WB35gIm3BpGyXTjC2UXIofnS/BYc93rl5rArzC2fbg5F5ByXpJV8ThoQ==
  template:
    metadata:
      creationTimestamp: null
      name: prowlarr-postgres-user
      namespace: postgres
    type: kubernetes.io/basic-auth
