---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-postgres-user
  namespace: postgres
spec:
  encryptedData:
    password: AgA/4Jl8+is8YIdg8wPVmwxlIhb2HMsEbtwqnw9HNybq5EPS6YA0SZbhoCSgF9v88xNlrx8KG7j+UV7PIqCnTTcpde1T5wge4rwPkfuoB+dlfmtSVMHgDTzndoSYxo2qOZbhnwFtuAbWy7Y8Zv+LXVE9YwtIK0q4x6UZRDV8Q1Eux3YwjDgKOpFpH8cw9gh+I8pnvNmC/0gXZbGPAbsyU930FbSuGhQDb72MLiwZe+p89N8dK1Efe02mEyHu0q/3yMxFKCezeozJcFBZsO0pPX2jNJlRTcjAazTo46wY1OO7xptpFECBRAf/MdyqO27L19NFCFVNz8lauvVW5CYQGP52GJcLfLoUShu0Ioj3ZsiGRGgIPLOh5vmOkY8/lRi0Eaokr+wXh9pUEkpxdjWZwhBsmNDOUX5FJKN6B8Xd2vwCxy6HReetLq0cX3KHziFVaUBWarq5ZKN+2IyfMqPi2UxmbzFf2hdbIzODorDPkC3tKZPnbe6s0QCB3TyraqxAdjAcGuy27WExhsSIEVJo9bG9tk2+7b8nhuVIrq1+QwdgO0icRmvqOUnoHWBog7HhFzTYEyGthbDHxdrVDcKB+lJcwJcpeloAbdDbx9Vt7eF2eAhV8YxfwyYY5W04zypRtUo6WUxX1UlJHYsVoqTMl7QzJ88uA6gNsSLctyw6p0VERpeM63msfrUb7UcnLJpLAa++cgHpvqP4hYrdQlkD81pywpnbGTO6O8tvIURp5Uw=
    username: AgAtP0otKTVgkfRKDeJbZvx62bnCL8HxGhTN/uk2/CFVHS1rYZygKauE7I9I5pXDLBemmq1Ouv+5rQCRfKwSUQ/wO1O16rv8qh/xQSvmxTH+SPrxbnV5uyexgucV079EnkXgN7u8K2LhOghtg0mMWXpiJ1uPGyUPposX+ionB9fsp2vy81iwAeBd+9HdtBevxMf2KUGyLbU9QKOGT+dY+XWWdduJ89Ph00wrYxlo8kgErGgVKBHk1Mi8fivQoymD3MPhtJ4I/MN/P3Forq8GTHPJ6MgPBu7JjYKCXIj0G7IrYzB4Enkdo7ZiD75mxkXG8OWjtslmItl/cTrE0yOlcPzK2QRxJwVhlm6rAGyRwtrH3fQI5MhY7Xing4f5XMRV+foOLKVOi0UfOK0YF2Q48y1WAOHlEy/Pk2igrrglet8rt31Z43NeKT2FyOuNPI3wUmKj7TpI1BLHRlFPR8EYO1m99GK6z72TBj1/ZBJlWZTg0P6kTdV0mRibdCRTZW21hmLyfDlWdrh7LjVuzjQ+6F0falWoy+Ndi9M5xrpeyT/eFGCi1nKv7VQ/cXlmktFRYMQ9wAvYvQZ02q52o+vUkT3q3TfoaqEI/nFWUnQdGYniwYpKd0I3hj9v+EdGubX7mq1kBoZK/nFQVNRPH76a418llNWySjo7oDxvea+2wiic6kWukE5sEEKBsZOi0XztLetxaLLGIZg=
  template:
    metadata:
      creationTimestamp: null
      name: radarr-postgres-user
      namespace: postgres
    type: kubernetes.io/basic-auth
