---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-postgres-user
  namespace: postgres
spec:
  encryptedData:
    password: AgAhEDNQAhBGF+FBeZ/MkjhFW9f9GLumzl6CLlNnJf0DKe0mrk9QgYXwhvXX/ionJ0uCGT1tW9pLdynKN82mga3sMqBpJgW90h8ck+nXEKj4tLBNvza7Badq3hXpyx0gEtXF4VAZxPlkpOlNwy2LZyP15IfNlGGQB3ggMagasL6nK4gOoMhKpMxv8dCGs3csnkzjOcpCngVZImpwwwJnksfdLcjP3Pnyrxd6WP/Fz2G8C1UWTdkBAw5tDZH2poW4p1PF9j5LtIyFhS5MktZICVOR+TUNgGFIxOUzqBerTl8a0uBwkSU2832xaEFZlR4IqlGP46r8RUTKJY6D+z3JTovK0dTFBFG6icrJ/IDCPlLB1HJP4RmpZlJKzUg824SwZMPeK4Kj52yx8ME1aaEGcO1SD/MtcdARJ1pF+BjNZ2WUnFYpfOe8D3Uvy7G/m51RCfRgyvcYxvODRrHrSU0ulQ+zt7ptxh4OPrTyWp4UVI42oanGwrrA+uV162OQf2ihPL15gV2iz5VRqnxKAwQTLzUbYVZu/WdAzsVq9t1/ssrwDNrygEIGHT4m8wmK7smNFcClFdvIoMmQSIfd1X7+zOTdTGGHXtqDgktZEbJLWZb+iZyfTTtOoSnxqGQ6LloBik8EDEvBc/vdzRR4tjjC0fxTAEYYPXwZKsj/0K1c36D3AfxWReNQLs+g0PQRbPThodh4AoNZUMM2/jWnLI14Tf2PULuYtlsvFpfPxP5+irQ=
    username: AgBD3MQ0+76q/XmdjnqjPu/V6IgflGc009UTC9rx1OBpYJxHUl2EVZzGeZs74xPnpja0Aq6Y9EdWEAOSe/f9ypGyxyAmuDd7iUogS/+6stEZY9SkV35lSdN7AqzPRNsbN4E4YcIqdpQdPNW9VJTHYQJEOuLYG7zcgpp8D1kk6EmY8tHMLJvwmJGrdtYL97K5vdfUq6v5krXp9IfSfpaSRncWL3poNFm0TOT7krG42Lz4o7oqDMfWa1cs2wWxX6n+mJTEiL0dV17UJZluKFz2xAQrG4GJprVku2nf//6NVPsr6fZyy/UGATxKncsI2E4QPIPV5T/OLBfUA1jSd+4EbF4utKhPGs64ALHEmKLjVMByyOH672zJJJplpMGZdXx3YAfhio/cVFy1N3ai6dBNs21gRuvQuaDDxrO3yCVzrvYn5vA37XHqdz/1iuK7YpgvyPEkvp/FbFCFtu4k3dnK+18RDJ0eg4uL8xzBaYuJG0+uB6ttJgAPDkIIraVy+HjGa4lsdMxcqo3jONkZYdgU5H6UKSXj00VRt2YJcjAVQC/f76jUZNjBB9i2QxLKUu3k5C3NqGxzuD9f8IRfZTD/cJv3bbzSrddRKsYZjJCNDHa6f+G4pC0dFEYvhvhE6/mTLj0ArtfPkAfJzcoOYNFubgnMqGYOIbQJwAk2yf6QH81GreZ/wioJwaD25xcfTrQoOUa5fyN8SaE=
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-postgres-user
      namespace: postgres
    type: kubernetes.io/basic-auth
