---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: teleport-postgres-user
  namespace: postgres
spec:
  encryptedData:
    password: AgBH+MhMc0KeCVOIudvvTmd6+MEeuzOXR6GyjnlUcKeuI+1X3KoS/HsG5+ZNsFqNREir3jY9d50ChdYAXZBzF0lJrr1ZRTw8k0KD+bjfLvya6OBnKJiNrvzyos3NgLL/X/DjzcbJxeEontJORCqC+rSKntdHiIa8FNx5YUPQ4IDjBi1Z7BMGnEo6Q9ywki+iBdhVz1NiOvEWW56MHKgTlt2QX1CMAH9d7Gt1WrNj/ad8vPiynBllsMn4/jg199+wOXMemyx6vJXgvJ1+KdEy1iz8GcxA6JpEoeWrbZzmrffR54pD4+chV3p5uZRR4cc00f7ZbILA2Etr4E8qUuLpj9OBaxuExMbE1Oe4eX1yWmUqbEs0rJLnKdJbIdzfXQLaT6XLUWEqMXq3MC/TvWbAPUGMYnpqCqBRLqcE8VTUJbVsUF0OfRldNYNabUFwOy58csqLMYMTxdqDX/nE2p+UEMDhtBi0ZCJL7Yy3iXaSEMtG/A7qHHTiCyt0I26aZVUqxkXgkHqxSWAVPPr33p2PSnyg5oMoRckhHveM+gsRL9JJro7gbGlaqHTVmKMa50AiVXR+uy38eCgFROmPUCUTT9zwSCausW73xwafvcuoIxV3nnbuMA9B9OcprVKuu3liWxIevMd5nYaTV82hLblCwU5xm65Prt1ohPQ5wRILVw06pY4sw51MIRl1gGwKKUapiCVDmGnRLtU9etNdirgSj0hAdQaqV5Jn7Vc=
    username: AgCe2sHFrhXjiiXb6+rcVWv9ecnZQiS2sIpvI1+A16WZjVO6HoQp/vjOao0b1L7tSL9lwBtVq4twtN4ZoXHPnmU3MXa/sXhS1k+C+fwgs5ld28l6pK3FCmSVNDQX9dPoFQDek0vq9G0DFqv8uChsyyYAkvp44YL0BxFLepWBOyQjBpDE8R5X9opWUmMweX/POyCMxjT68LtWux4lRZ3GRd8Lsqo4HTK+Vwi8nYTdvL5mCQ1o3XTtP0/q2vwvKwcG3LVuJ1uRgWB4OP/9heNYWM5cl7p9e6KA5paUt16PxWWU0RdXgZ6fExmACuCqA2YSTanJX60bh6TO2UyerusdOV7zX4HZZaMZqq1UzkXxRO0VLGQx8qEZHmuC6KQCgUEp6C5EfbaAAiQiNEwZcMoZOQjLy2A5oIzLsS32s70TDUJp/sbpNRu+/8gery1Npx73bfrXP+GMGD+gRgMsONFy6dCCHqkPE0Ua/f7/ol7IBq+2+xeDqCSaFUtCd8uCu4nRIzTSiQyneMLKAWpggl9A4+fJH4hYuu3I24QJdVervOxm8Tq9P4ckP5nWqZ6T4btoRVwo0b9W6bRy6vDWOj7fROIyRj7HBt5QAWaj7f1xa7kbpydF+Jg2VZo1P2t0qbG0QRhtamvEggNWVWgn9+55Xfm2nUfkO+wR1L8ZqsKp3KxbpvmTr2rseT3kLHZNOE/JA7nT1KwwsqmY7w==
  template:
    metadata:
      creationTimestamp: null
      name: teleport-postgres-user
      namespace: postgres
    type: kubernetes.io/basic-auth
