---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: teleport-postgres-user
  namespace: postgres
spec:
  encryptedData:
    password: AgBL84xNsBbdjaaFvqD5qHVaaKKYtwyQDkIX4hW5h4jbLQ6NB+V9ZpaiKY6yfZyDUD0M3WAIxdIQXxskTwXKQ+93cMLlGgTR1Dx6pb7AuIXfUg5QWUF6q9GqcL0c56lY7p1XLcTtu/Tm/fTyS+2y2G8+8bOBT5onC+Noz41cc1c/u+/7NI3MGiuV2orAYrMv6cnmE48ndFAbTFmdGVBnRAQ5od/9tAT+5uUYd+NvaIbKJhnLaBf1FLG+Mbq8suzoBtUlufLXVYtc9funi8ohApOjkTL9YpkmuUPNF+JibFAJpoXHUSP4eXGfMYKYiJEwHpWKLy0tLzVqfAjUxjxjHWkAenVvzwnOSZmLWvJoS7oG1jNy+LBOPIOcBtPkhhfpT2A6y71FsKl6OXOuWdz5ENeqFp9RjIy2PElMDYv0lTW8gNArAGSwUqI5KDgEGqHZW62HvS6kVeTLWJm9d3NusG56x+JbUHLDqEmjY8vGGLa+P8NpLf7phKgoW0Bp464jTZdmM8PdSuu9mggwxuvFb6PymBbfwXBS6qJgrv2ziBfW5Gd78ALChQv4IGXVVtYWfurVEtU/Nw2ulTKYbDuQLFeVXaA8kQse2z2DUA6SYxI4j26sOBevQac2i8v3e+6r8VW4GjxpxO7+XpV6VGY8OKUx9JqZ+1TOTltk0SUrIi4stfSbTBFZcYQnCLjkGUxTqudBw4Nlk7NgzcsaT4v0b4dfDzDEDWDOBTU=
    username: AgACfnob76JKfmit1suDbQO4D7YneqW+YaelpSF94y90lmCdNfpvfgJJWzCbxvwjduvN/DPhVXopsK9LpmLLa2jxaR2f9Pz7qGVoXJWOFzzGUiq/mtwKjayl7CvaJucwi5YXJoyJJDlho72nF9IQDSLMC37mIE8jM64KsH+M/4FLB3wlxBaVBJ8hGIYSK5/emLMH7Qfb8z0+RbUZxrQ927w1PE9t3YUd7H215zaViDDLWaxpuomt9j2VESwMNDsd3D1alB/pGIerUKsyp5u44FRhTV1gE+GLuborFCkFzq+gzhTSnBB+2cfMGwTMpmdio4O/SGes4EOSdZ8SGop57mv2KdCqHTjHdmi3RwOvGTOHixyKCuhrAX0YiJHKMK2BCPraModOd23GN2p3KbmGuvXOlO/HdM6zX4qmAXMx9Vsupq+cu7jHkJyeaj14aRTdfrfmKCPS9rDHr8gw7T53aI6MJnA0LllsQDelDLnyJWKqwZHTcdfKn531WVWs5PF4ya6sVyNbEgzpUJXMbsKjbDhqlZ18kJzJX88BEgk8ABLknAmJtSVhmMbYaWUPqhdwGNKNbL6kJ/RQsP6hEg7P2KLAvzQRjaOQ6sTt7Nes59iuLndQB8XyJw+8hTymLlBEFBUYwjd9E6Xeoe//T3yQ35sQmr0z+GNCkgX3VFsIgRLslLxjee3I/8uWbJfWVN5lupZ4g2/vJs5v+g==
  template:
    metadata:
      creationTimestamp: null
      name: teleport-postgres-user
      namespace: postgres
    type: kubernetes.io/basic-auth
